"""Nasdaq Composite constituent tickers (common stock, ADRs, REITs, etc. -
warrants/rights/units/preferred/notes and dual-class-suffix symbols
filtered out) mapped to a sector label, used only by the Nasdaq ranking
tab - independent of the hand-curated dashboard watchlist in symbols.py.

Sourced from https://github.com/rreichel3/US-Stock-Symbols (refreshed
daily by that repo's own GitHub Action off Nasdaq's own listings), snapshot
taken 2026-09-16. Sector labels come from Nasdaq's own (non-GICS)
classification and are blank for some newer/thinly-covered listings, shown
here as "Unknown". Nothing here is loaded live to keep a ranking run
reproducible and rate-limit-friendly - the actual constituent list drifts
over time (new listings, delistings) and this snapshot will too.
"""

NASDAQ_SECTORS: dict[str, str] = {
    "AACG": "Real Estate",
    "AACI": "Finance",
    "AACO": "Unknown",
    "AACP": "Finance",
    "AAL": "Consumer Discretionary",
    "AAME": "Finance",
    "AAOI": "Technology",
    "AAON": "Industrials",
    "AAPG": "Health Care",
    "AAPL": "Technology",
    "AARD": "Health Care",
    "ABAT": "Industrials",
    "ABCL": "Health Care",
    "ABEO": "Health Care",
    "ABLV": "Consumer Discretionary",
    "ABNB": "Consumer Discretionary",
    "ABOS": "Health Care",
    "ABSI": "Health Care",
    "ABTC": "Finance",
    "ABTS": "Finance",
    "ABUS": "Health Care",
    "ABVC": "Health Care",
    "ABVX": "Health Care",
    "ACAA": "Finance",
    "ACAD": "Health Care",
    "ACB": "Health Care",
    "ACCL": "Consumer Discretionary",
    "ACDC": "Energy",
    "ACET": "Health Care",
    "ACFN": "Consumer Discretionary",
    "ACGC": "Finance",
    "ACGL": "Finance",
    "ACHC": "Health Care",
    "ACHV": "Health Care",
    "ACIC": "Finance",
    "ACIU": "Health Care",
    "ACIW": "Technology",
    "ACLS": "Technology",
    "ACMR": "Technology",
    "ACNB": "Finance",
    "ACNT": "Industrials",
    "ACOG": "Unknown",
    "ACON": "Health Care",
    "ACRS": "Health Care",
    "ACRV": "Health Care",
    "ACT": "Finance",
    "ACTG": "Miscellaneous",
    "ACTU": "Health Care",
    "ACXP": "Health Care",
    "ADAC": "Unknown",
    "ADAG": "Health Care",
    "ADAM": "Real Estate",
    "ADBE": "Technology",
    "ADBT": "Technology",
    "ADEA": "Telecommunications",
    "ADGM": "Health Care",
    "ADI": "Technology",
    "ADIL": "Health Care",
    "ADMA": "Health Care",
    "ADP": "Technology",
    "ADPT": "Health Care",
    "ADSE": "Consumer Discretionary",
    "ADSK": "Technology",
    "ADTN": "Utilities",
    "ADUR": "Industrials",
    "ADUS": "Health Care",
    "ADV": "Consumer Discretionary",
    "ADVB": "Health Care",
    "ADXN": "Health Care",
    "AEAQ": "Unknown",
    "AEBI": "Industrials",
    "AEC": "Basic Materials",
    "AEHL": "Consumer Discretionary",
    "AEHR": "Industrials",
    "AEI": "Finance",
    "AEIS": "Technology",
    "AEMD": "Health Care",
    "AENT": "Consumer Discretionary",
    "AEP": "Utilities",
    "AERT": "Consumer Discretionary",
    "AESP": "Finance",
    "AEVA": "Consumer Discretionary",
    "AEYE": "Technology",
    "AFCG": "Finance",
    "AFJK": "Unknown",
    "AFRI": "Consumer Staples",
    "AFRM": "Finance",
    "AFYA": "Real Estate",
    "AGCC": "Consumer Staples",
    "AGEN": "Health Care",
    "AGIO": "Health Care",
    "AGMB": "Health Care",
    "AGMH": "Technology",
    "AGNC": "Real Estate",
    "AGNT": "Finance",
    "AGPU": "Health Care",
    "AGRZ": "Consumer Staples",
    "AGYS": "Technology",
    "AHCO": "Health Care",
    "AHG": "Consumer Discretionary",
    "AHMA": "Consumer Discretionary",
    "AIAI": "Technology",
    "AIBZ": "Consumer Discretionary",
    "AIDX": "Health Care",
    "AIFA": "Consumer Discretionary",
    "AIFC": "Finance",
    "AIFF": "Technology",
    "AIFU": "Finance",
    "AIIO": "Industrials",
    "AIIR": "Consumer Discretionary",
    "AIMD": "Technology",
    "AIOS": "Industrials",
    "AIOT": "Telecommunications",
    "AIP": "Technology",
    "AIRE": "Finance",
    "AIRG": "Technology",
    "AIRJ": "Industrials",
    "AIRO": "Industrials",
    "AIRS": "Health Care",
    "AIRT": "Consumer Discretionary",
    "AISP": "Technology",
    "AIXC": "Finance",
    "AIXI": "Technology",
    "AKAM": "Consumer Discretionary",
    "AKAN": "Health Care",
    "AKBA": "Health Care",
    "AKTS": "Health Care",
    "AKTX": "Health Care",
    "ALAB": "Technology",
    "ALAR": "Technology",
    "ALCO": "Consumer Staples",
    "ALDF": "Unknown",
    "ALDX": "Health Care",
    "ALEC": "Health Care",
    "ALF": "Unknown",
    "ALGM": "Technology",
    "ALGN": "Health Care",
    "ALGS": "Health Care",
    "ALGT": "Consumer Discretionary",
    "ALHC": "Health Care",
    "ALIS": "Unknown",
    "ALKS": "Health Care",
    "ALKT": "Technology",
    "ALLO": "Health Care",
    "ALLR": "Health Care",
    "ALLT": "Telecommunications",
    "ALM": "Basic Materials",
    "ALMR": "Industrials",
    "ALMS": "Health Care",
    "ALMU": "Technology",
    "ALNT": "Industrials",
    "ALNY": "Health Care",
    "ALOV": "Unknown",
    "ALOY": "Basic Materials",
    "ALP": "Finance",
    "ALPS": "Health Care",
    "ALPX": "Finance",
    "ALRM": "Technology",
    "ALRS": "Finance",
    "ALT": "Health Care",
    "ALTI": "Finance",
    "ALTO": "Industrials",
    "ALVO": "Health Care",
    "ALXO": "Health Care",
    "ALZN": "Health Care",
    "AMAC": "Finance",
    "AMAL": "Finance",
    "AMAN": "Finance",
    "AMAT": "Technology",
    "AMBA": "Technology",
    "AMBR": "Finance",
    "AMCI": "Consumer Discretionary",
    "AMCX": "Telecommunications",
    "AMD": "Technology",
    "AMGN": "Health Care",
    "AMIX": "Health Care",
    "AMKR": "Technology",
    "AMLX": "Health Care",
    "AMOD": "Miscellaneous",
    "AMPG": "Telecommunications",
    "AMPH": "Health Care",
    "AMPL": "Technology",
    "AMRN": "Health Care",
    "AMRX": "Health Care",
    "AMSC": "Consumer Discretionary",
    "AMSF": "Finance",
    "AMSS": "Consumer Staples",
    "AMST": "Technology",
    "AMTX": "Industrials",
    "AMZN": "Consumer Discretionary",
    "ANAB": "Health Care",
    "ANDE": "Industrials",
    "ANGH": "Consumer Discretionary",
    "ANGI": "Consumer Discretionary",
    "ANGO": "Health Care",
    "ANIK": "Health Care",
    "ANIP": "Health Care",
    "ANIX": "Health Care",
    "ANL": "Health Care",
    "ANNA": "Energy",
    "ANNX": "Health Care",
    "ANPA": "Consumer Discretionary",
    "ANTA": "Finance",
    "ANTX": "Health Care",
    "ANY": "Finance",
    "AOSL": "Technology",
    "AOUT": "Consumer Discretionary",
    "APA": "Energy",
    "APAC": "Finance",
    "APC": "Energy",
    "APEI": "Real Estate",
    "API": "Technology",
    "APLD": "Technology",
    "APLM": "Health Care",
    "APMC": "Finance",
    "APMD": "Health Care",
    "APOG": "Consumer Discretionary",
    "APP": "Technology",
    "APPF": "Technology",
    "APPN": "Technology",
    "APPS": "Miscellaneous",
    "APRE": "Health Care",
    "APUR": "Finance",
    "APVO": "Health Care",
    "APWC": "Industrials",
    "APXT": "Finance",
    "APYX": "Health Care",
    "AQB": "Consumer Staples",
    "AQMS": "Industrials",
    "AQST": "Health Care",
    "ARAI": "Consumer Discretionary",
    "ARAY": "Health Care",
    "ARBB": "Technology",
    "ARBE": "Technology",
    "ARBK": "Finance",
    "ARCB": "Industrials",
    "ARCC": "Finance",
    "ARCI": "Unknown",
    "ARCL": "Finance",
    "ARCT": "Health Care",
    "ARDX": "Health Care",
    "AREC": "Energy",
    "ARGX": "Health Care",
    "ARHS": "Consumer Discretionary",
    "ARKO": "Consumer Staples",
    "ARKR": "Consumer Discretionary",
    "ARM": "Technology",
    "AROW": "Finance",
    "ARQ": "Industrials",
    "ARQQ": "Technology",
    "ARQT": "Health Care",
    "ARRY": "Technology",
    "ARTC": "Finance",
    "ARTL": "Health Care",
    "ARTNA": "Utilities",
    "ARTV": "Health Care",
    "ARTW": "Industrials",
    "ARVN": "Health Care",
    "ARWR": "Health Care",
    "ARXS": "Industrials",
    "ASBP": "Health Care",
    "ASLE": "Consumer Discretionary",
    "ASMB": "Health Care",
    "ASML": "Technology",
    "ASND": "Health Care",
    "ASO": "Consumer Discretionary",
    "ASPC": "Finance",
    "ASPI": "Industrials",
    "ASPS": "Consumer Discretionary",
    "ASRV": "Finance",
    "ASST": "Finance",
    "ASTC": "Industrials",
    "ASTE": "Industrials",
    "ASTH": "Consumer Discretionary",
    "ASTI": "Technology",
    "ASTL": "Industrials",
    "ASTS": "Consumer Discretionary",
    "ASUR": "Technology",
    "ASYS": "Technology",
    "ATAT": "Consumer Discretionary",
    "ATCX": "Basic Materials",
    "ATEC": "Health Care",
    "ATER": "Consumer Discretionary",
    "ATEX": "Telecommunications",
    "ATGL": "Technology",
    "ATHE": "Health Care",
    "ATHR": "Technology",
    "ATII": "Unknown",
    "ATLC": "Finance",
    "ATLO": "Finance",
    "ATLQ": "Finance",
    "ATLX": "Industrials",
    "ATNI": "Telecommunications",
    "ATOM": "Technology",
    "ATOS": "Health Care",
    "ATPC": "Health Care",
    "ATRA": "Health Care",
    "ATRC": "Health Care",
    "ATRO": "Industrials",
    "ATTO": "Health Care",
    "ATTT": "Consumer Discretionary",
    "ATXG": "Consumer Discretionary",
    "ATYR": "Health Care",
    "AUBN": "Finance",
    "AUC": "Consumer Discretionary",
    "AUDC": "Utilities",
    "AUGO": "Basic Materials",
    "AUID": "Technology",
    "AUPH": "Health Care",
    "AUR": "Technology",
    "AURA": "Health Care",
    "AURE": "Finance",
    "AUTL": "Health Care",
    "AUUD": "Technology",
    "AVAH": "Health Care",
    "AVAT": "Finance",
    "AVAV": "Industrials",
    "AVBH": "Finance",
    "AVBP": "Health Care",
    "AVGO": "Technology",
    "AVIR": "Health Care",
    "AVLN": "Health Care",
    "AVNW": "Technology",
    "AVO": "Consumer Staples",
    "AVPT": "Technology",
    "AVR": "Health Care",
    "AVT": "Technology",
    "AVTX": "Health Care",
    "AVX": "Finance",
    "AVXL": "Health Care",
    "AWRE": "Technology",
    "AXG": "Finance",
    "AXGN": "Health Care",
    "AXIN": "Finance",
    "AXON": "Industrials",
    "AXSM": "Health Care",
    "AXTI": "Technology",
    "AYA": "Basic Materials",
    "AYTU": "Health Care",
    "AZ": "Industrials",
    "AZI": "Consumer Discretionary",
    "AZIO": "Consumer Discretionary",
    "AZTA": "Technology",
    "BACC": "Finance",
    "BAER": "Industrials",
    "BAFN": "Finance",
    "BAND": "Technology",
    "BANF": "Finance",
    "BANL": "Energy",
    "BANR": "Finance",
    "BANX": "Finance",
    "BAOS": "Consumer Discretionary",
    "BATRA": "Consumer Discretionary",
    "BATRK": "Consumer Discretionary",
    "BBCP": "Consumer Discretionary",
    "BBGI": "Consumer Discretionary",
    "BBIO": "Health Care",
    "BBLG": "Health Care",
    "BBNX": "Health Care",
    "BBOT": "Health Care",
    "BBSI": "Consumer Discretionary",
    "BCAL": "Finance",
    "BCAX": "Health Care",
    "BCBP": "Finance",
    "BCCQ": "Finance",
    "BCDA": "Health Care",
    "BCG": "Finance",
    "BCIC": "Finance",
    "BCML": "Finance",
    "BCPC": "Industrials",
    "BCRX": "Health Care",
    "BCTX": "Health Care",
    "BCYC": "Health Care",
    "BDCI": "Finance",
    "BDMD": "Health Care",
    "BDRX": "Health Care",
    "BDSX": "Health Care",
    "BDTX": "Health Care",
    "BEAG": "Unknown",
    "BEAM": "Health Care",
    "BEAT": "Health Care",
    "BEEM": "Miscellaneous",
    "BEEP": "Finance",
    "BELFA": "Unknown",
    "BELFB": "Unknown",
    "BENF": "Finance",
    "BETR": "Finance",
    "BFC": "Finance",
    "BFRG": "Health Care",
    "BFRI": "Health Care",
    "BFST": "Finance",
    "BGC": "Finance",
    "BGDE": "Finance",
    "BGIN": "Finance",
    "BGL": "Basic Materials",
    "BGLC": "Health Care",
    "BGM": "Health Care",
    "BGMS": "Health Care",
    "BHAV": "Finance",
    "BHF": "Finance",
    "BHRB": "Finance",
    "BHST": "Unknown",
    "BIAF": "Health Care",
    "BID": "Finance",
    "BIDU": "Technology",
    "BIIB": "Health Care",
    "BILI": "Technology",
    "BIOA": "Health Care",
    "BIOT": "Consumer Discretionary",
    "BIOX": "Industrials",
    "BIRD": "Consumer Discretionary",
    "BIVI": "Health Care",
    "BIXI": "Unknown",
    "BIYA": "Consumer Discretionary",
    "BJDX": "Health Care",
    "BJRI": "Consumer Discretionary",
    "BKHA": "Health Care",
    "BKNG": "Consumer Discretionary",
    "BKR": "Consumer Discretionary",
    "BKYI": "Technology",
    "BL": "Technology",
    "BLBD": "Consumer Discretionary",
    "BLDP": "Energy",
    "BLFS": "Health Care",
    "BLIN": "Technology",
    "BLIV": "Technology",
    "BLKB": "Technology",
    "BLLN": "Health Care",
    "BLMN": "Consumer Discretionary",
    "BLNE": "Finance",
    "BLNK": "Miscellaneous",
    "BLRK": "Unknown",
    "BLRX": "Health Care",
    "BLSM": "Health Care",
    "BLTE": "Health Care",
    "BLUW": "Unknown",
    "BLZE": "Technology",
    "BLZR": "Finance",
    "BMBL": "Technology",
    "BMEA": "Health Care",
    "BMGL": "Health Care",
    "BMHL": "Finance",
    "BMM": "Unknown",
    "BMR": "Technology",
    "BMRA": "Health Care",
    "BMRC": "Finance",
    "BMRN": "Health Care",
    "BNAI": "Technology",
    "BNC": "Consumer Staples",
    "BNGO": "Industrials",
    "BNKK": "Consumer Discretionary",
    "BNR": "Health Care",
    "BNTC": "Health Care",
    "BNTX": "Health Care",
    "BODI": "Consumer Discretionary",
    "BOF": "Consumer Staples",
    "BOKF": "Finance",
    "BOLD": "Health Care",
    "BOLT": "Health Care",
    "BON": "Health Care",
    "BOOM": "Industrials",
    "BOSC": "Telecommunications",
    "BOT": "Unknown",
    "BOTJ": "Finance",
    "BOXL": "Real Estate",
    "BPAC": "Unknown",
    "BPOP": "Finance",
    "BPRN": "Finance",
    "BRAG": "Technology",
    "BRAI": "Technology",
    "BRBI": "Finance",
    "BRCB": "Consumer Discretionary",
    "BREZ": "Finance",
    "BRFH": "Consumer Staples",
    "BRID": "Consumer Staples",
    "BRKH": "Finance",
    "BRKR": "Industrials",
    "BRLS": "Consumer Staples",
    "BRLT": "Consumer Discretionary",
    "BRNX": "Industrials",
    "BRR": "Finance",
    "BRTM": "Finance",
    "BRTX": "Health Care",
    "BRUN": "Technology",
    "BRVE": "Health Care",
    "BRZE": "Technology",
    "BSAA": "Finance",
    "BSBK": "Finance",
    "BSEM": "Health Care",
    "BSET": "Consumer Discretionary",
    "BSIN": "Energy",
    "BSP": "Technology",
    "BSRR": "Finance",
    "BSVN": "Finance",
    "BSY": "Technology",
    "BTBD": "Consumer Discretionary",
    "BTBT": "Finance",
    "BTCS": "Finance",
    "BTCT": "Finance",
    "BTDR": "Finance",
    "BTLN": "Technology",
    "BTMD": "Health Care",
    "BTOC": "Consumer Discretionary",
    "BTQ": "Unknown",
    "BTSG": "Health Care",
    "BTTC": "Health Care",
    "BULL": "Finance",
    "BUSE": "Finance",
    "BUUU": "Consumer Discretionary",
    "BVC": "Finance",
    "BVFL": "Finance",
    "BVS": "Health Care",
    "BWAY": "Health Care",
    "BWB": "Finance",
    "BWEN": "Telecommunications",
    "BWFG": "Finance",
    "BWIN": "Finance",
    "BWMN": "Consumer Discretionary",
    "BXBL": "Consumer Discretionary",
    "BYAH": "Consumer Discretionary",
    "BYFC": "Finance",
    "BYND": "Consumer Staples",
    "BYRN": "Miscellaneous",
    "BYSI": "Health Care",
    "BZ": "Technology",
    "BZAI": "Technology",
    "BZFD": "Consumer Discretionary",
    "BZUN": "Consumer Discretionary",
    "CAAS": "Consumer Discretionary",
    "CABA": "Health Care",
    "CABR": "Consumer Discretionary",
    "CAC": "Finance",
    "CACC": "Finance",
    "CADL": "Health Care",
    "CAE": "Miscellaneous",
    "CAES": "Finance",
    "CAI": "Health Care",
    "CAII": "Finance",
    "CAKE": "Consumer Discretionary",
    "CALC": "Health Care",
    "CALM": "Consumer Staples",
    "CAMP": "Health Care",
    "CAMT": "Technology",
    "CAN": "Finance",
    "CAPN": "Unknown",
    "CAPR": "Health Care",
    "CAPS": "Health Care",
    "CAQ": "Unknown",
    "CAR": "Consumer Discretionary",
    "CARE": "Finance",
    "CARG": "Technology",
    "CARL": "Health Care",
    "CART": "Consumer Discretionary",
    "CASH": "Finance",
    "CASS": "Consumer Discretionary",
    "CAST": "Technology",
    "CASY": "Consumer Discretionary",
    "CATY": "Finance",
    "CBAT": "Miscellaneous",
    "CBC": "Finance",
    "CBFV": "Finance",
    "CBIO": "Health Care",
    "CBK": "Finance",
    "CBLL": "Health Care",
    "CBNK": "Finance",
    "CBRL": "Consumer Discretionary",
    "CBRS": "Technology",
    "CBSH": "Finance",
    "CBUS": "Industrials",
    "CCAP": "Finance",
    "CCAQ": "Finance",
    "CCB": "Finance",
    "CCBG": "Finance",
    "CCC": "Technology",
    "CCCC": "Health Care",
    "CCCT": "Unknown",
    "CCD": "Finance",
    "CCEC": "Consumer Discretionary",
    "CCEP": "Consumer Staples",
    "CCG": "Finance",
    "CCHH": "Consumer Discretionary",
    "CCII": "Unknown",
    "CCLD": "Technology",
    "CCNE": "Finance",
    "CCOI": "Consumer Discretionary",
    "CCSI": "Technology",
    "CCTG": "Consumer Discretionary",
    "CCXI": "Finance",
    "CD": "Finance",
    "CDIO": "Health Care",
    "CDLX": "Technology",
    "CDNA": "Health Care",
    "CDNL": "Industrials",
    "CDNS": "Technology",
    "CDRO": "Consumer Discretionary",
    "CDT": "Health Care",
    "CDTG": "Industrials",
    "CDW": "Consumer Discretionary",
    "CDXS": "Industrials",
    "CDZI": "Utilities",
    "CDZIP": "Utilities",
    "CECO": "Industrials",
    "CEG": "Utilities",
    "CELC": "Health Care",
    "CELH": "Consumer Staples",
    "CELU": "Health Care",
    "CELZ": "Health Care",
    "CENN": "Industrials",
    "CENT": "Consumer Discretionary",
    "CENTA": "Consumer Discretionary",
    "CENX": "Industrials",
    "CEPF": "Finance",
    "CEPL": "Industrials",
    "CEPO": "Finance",
    "CEPS": "Finance",
    "CEPV": "Unknown",
    "CERS": "Health Care",
    "CERT": "Technology",
    "CETX": "Technology",
    "CETY": "Utilities",
    "CEVA": "Technology",
    "CFBK": "Finance",
    "CFFI": "Finance",
    "CFFN": "Finance",
    "CG": "Finance",
    "CGBD": "Finance",
    "CGC": "Health Care",
    "CGCF": "Finance",
    "CGEM": "Health Care",
    "CGEN": "Health Care",
    "CGNT": "Technology",
    "CGNX": "Industrials",
    "CGO": "Finance",
    "CGON": "Health Care",
    "CGTL": "Technology",
    "CGTX": "Health Care",
    "CHA": "Consumer Discretionary",
    "CHAI": "Telecommunications",
    "CHAR": "Unknown",
    "CHCI": "Finance",
    "CHCO": "Finance",
    "CHDN": "Consumer Discretionary",
    "CHEC": "Unknown",
    "CHEF": "Consumer Discretionary",
    "CHGA": "Technology",
    "CHI": "Finance",
    "CHKP": "Technology",
    "CHMG": "Finance",
    "CHNR": "Basic Materials",
    "CHPG": "Unknown",
    "CHR": "Technology",
    "CHRD": "Energy",
    "CHRN": "Industrials",
    "CHRS": "Health Care",
    "CHRW": "Industrials",
    "CHSN": "Consumer Staples",
    "CHTR": "Telecommunications",
    "CHW": "Finance",
    "CHY": "Finance",
    "CHYM": "Finance",
    "CIFR": "Finance",
    "CIGI": "Finance",
    "CIGL": "Consumer Discretionary",
    "CIIT": "Telecommunications",
    "CINF": "Finance",
    "CING": "Health Care",
    "CIRC": "Industrials",
    "CISO": "Consumer Discretionary",
    "CISS": "Consumer Discretionary",
    "CIVB": "Finance",
    "CJMB": "Consumer Discretionary",
    "CLAR": "Consumer Discretionary",
    "CLBK": "Finance",
    "CLBT": "Technology",
    "CLDX": "Health Care",
    "CLFD": "Utilities",
    "CLGN": "Health Care",
    "CLIK": "Consumer Discretionary",
    "CLIR": "Industrials",
    "CLLS": "Health Care",
    "CLMB": "Technology",
    "CLMT": "Energy",
    "CLNE": "Utilities",
    "CLNN": "Health Care",
    "CLOV": "Health Care",
    "CLPS": "Technology",
    "CLPT": "Health Care",
    "CLRB": "Health Care",
    "CLRO": "Utilities",
    "CLSK": "Finance",
    "CLST": "Finance",
    "CLWT": "Consumer Discretionary",
    "CLYM": "Health Care",
    "CMCO": "Industrials",
    "CMCSA": "Telecommunications",
    "CMCT": "Real Estate",
    "CME": "Finance",
    "CMMB": "Health Care",
    "CMND": "Health Care",
    "CMPR": "Consumer Discretionary",
    "CMPS": "Health Care",
    "CMPX": "Health Care",
    "CMRC": "Technology",
    "CMTL": "Technology",
    "CMTV": "Finance",
    "CNCK": "Finance",
    "CNDT": "Consumer Discretionary",
    "CNET": "Technology",
    "CNEY": "Industrials",
    "CNL": "Unknown",
    "CNOB": "Finance",
    "CNSP": "Health Care",
    "CNSY": "Health Care",
    "CNTB": "Health Care",
    "CNTN": "Health Care",
    "CNTX": "Health Care",
    "CNTY": "Consumer Discretionary",
    "CNVS": "Consumer Discretionary",
    "CNXC": "Technology",
    "CNXN": "Consumer Discretionary",
    "CNXU": "Health Care",
    "COAG": "Health Care",
    "COCH": "Health Care",
    "COCO": "Consumer Staples",
    "COCP": "Health Care",
    "CODA": "Industrials",
    "CODX": "Health Care",
    "COFS": "Finance",
    "COGT": "Health Care",
    "COHU": "Industrials",
    "COIN": "Finance",
    "COKE": "Consumer Staples",
    "COLA": "Finance",
    "COLB": "Finance",
    "COLL": "Health Care",
    "COLM": "Consumer Discretionary",
    "COO": "Health Care",
    "COOT": "Consumer Staples",
    "CORT": "Health Care",
    "CORZ": "Finance",
    "COSM": "Health Care",
    "COST": "Consumer Discretionary",
    "COYA": "Health Care",
    "CPB": "Consumer Staples",
    "CPBI": "Finance",
    "CPHC": "Consumer Discretionary",
    "CPIX": "Health Care",
    "CPOP": "Consumer Discretionary",
    "CPRT": "Consumer Discretionary",
    "CPSH": "Consumer Discretionary",
    "CPSS": "Finance",
    "CPZ": "Finance",
    "CRAC": "Unknown",
    "CRAI": "Consumer Discretionary",
    "CRAN": "Finance",
    "CRAQ": "Finance",
    "CRBP": "Health Care",
    "CRBU": "Health Care",
    "CRCT": "Technology",
    "CRDF": "Health Care",
    "CRDL": "Health Care",
    "CRDO": "Technology",
    "CRE": "Consumer Discretionary",
    "CRESY": "Finance",
    "CREX": "Technology",
    "CRGO": "Industrials",
    "CRIS": "Health Care",
    "CRMD": "Health Care",
    "CRML": "Basic Materials",
    "CRMT": "Consumer Discretionary",
    "CRNC": "Technology",
    "CRNT": "Technology",
    "CRON": "Health Care",
    "CROX": "Consumer Discretionary",
    "CRSP": "Health Care",
    "CRSR": "Technology",
    "CRTO": "Consumer Discretionary",
    "CRUS": "Technology",
    "CRVL": "Finance",
    "CRVO": "Health Care",
    "CRVS": "Health Care",
    "CRWD": "Technology",
    "CRWS": "Consumer Discretionary",
    "CRWV": "Technology",
    "CSAI": "Technology",
    "CSBR": "Health Care",
    "CSCO": "Telecommunications",
    "CSGP": "Finance",
    "CSHR": "Finance",
    "CSIQ": "Technology",
    "CSPI": "Technology",
    "CSQ": "Finance",
    "CSTE": "Industrials",
    "CSTL": "Health Care",
    "CSWC": "Consumer Discretionary",
    "CSX": "Industrials",
    "CTAA": "Finance",
    "CTAS": "Industrials",
    "CTBI": "Finance",
    "CTKB": "Industrials",
    "CTMX": "Health Care",
    "CTNM": "Health Care",
    "CTNT": "Consumer Discretionary",
    "CTOR": "Health Care",
    "CTRM": "Consumer Discretionary",
    "CTRN": "Consumer Discretionary",
    "CTSH": "Technology",
    "CTSO": "Health Care",
    "CTW": "Technology",
    "CTXR": "Health Care",
    "CUB": "Industrials",
    "CUE": "Health Care",
    "CULP": "Consumer Discretionary",
    "CUPR": "Health Care",
    "CURI": "Consumer Discretionary",
    "CURR": "Consumer Discretionary",
    "CURX": "Health Care",
    "CUVL": "Miscellaneous",
    "CV": "Health Care",
    "CVBF": "Finance",
    "CVCO": "Consumer Discretionary",
    "CVGI": "Consumer Discretionary",
    "CVKD": "Health Care",
    "CVLT": "Technology",
    "CVRX": "Health Care",
    "CVV": "Technology",
    "CWBC": "Finance",
    "CWCO": "Utilities",
    "CWD": "Finance",
    "CWST": "Utilities",
    "CXAI": "Technology",
    "CXDO": "Telecommunications",
    "CXII": "Finance",
    "CYAB": "Technology",
    "CYCU": "Technology",
    "CYN": "Technology",
    "CYPH": "Health Care",
    "CYRX": "Health Care",
    "CYTK": "Health Care",
    "CZFS": "Finance",
    "CZNC": "Finance",
    "CZR": "Consumer Discretionary",
    "CZWI": "Finance",
    "DAAQ": "Finance",
    "DAIC": "Technology",
    "DAIO": "Industrials",
    "DAKT": "Consumer Discretionary",
    "DARE": "Health Care",
    "DASH": "Consumer Discretionary",
    "DAVE": "Finance",
    "DBCA": "Finance",
    "DBGI": "Consumer Discretionary",
    "DBVT": "Health Care",
    "DBX": "Technology",
    "DCBO": "Technology",
    "DCGO": "Health Care",
    "DCOY": "Health Care",
    "DCTH": "Health Care",
    "DCX": "Industrials",
    "DDI": "Technology",
    "DDOG": "Technology",
    "DEFT": "Finance",
    "DERM": "Health Care",
    "DETX": "Industrials",
    "DFDV": "Finance",
    "DFLI": "Miscellaneous",
    "DFNS": "Consumer Discretionary",
    "DFSC": "Technology",
    "DFTX": "Health Care",
    "DGICA": "Finance",
    "DGICB": "Finance",
    "DGII": "Telecommunications",
    "DGNX": "Technology",
    "DGXX": "Finance",
    "DH": "Technology",
    "DHC": "Real Estate",
    "DIBS": "Consumer Discretionary",
    "DIOD": "Technology",
    "DJCO": "Consumer Discretionary",
    "DJT": "Technology",
    "DKI": "Technology",
    "DKNG": "Consumer Discretionary",
    "DLHC": "Consumer Discretionary",
    "DLO": "Consumer Discretionary",
    "DLPN": "Consumer Discretionary",
    "DLTH": "Consumer Discretionary",
    "DLTR": "Consumer Discretionary",
    "DLXY": "Energy",
    "DMAA": "Unknown",
    "DMAC": "Health Care",
    "DMII": "Finance",
    "DMRA": "Health Care",
    "DMRC": "Technology",
    "DNLI": "Health Care",
    "DNMX": "Finance",
    "DNTH": "Health Care",
    "DNUT": "Consumer Staples",
    "DOCU": "Technology",
    "DOGZ": "Consumer Discretionary",
    "DOMH": "Finance",
    "DOMO": "Technology",
    "DOO": "Consumer Discretionary",
    "DORM": "Consumer Discretionary",
    "DOX": "Technology",
    "DOYU": "Technology",
    "DPRO": "Industrials",
    "DPU": "Consumer Discretionary",
    "DPZ": "Consumer Discretionary",
    "DRCT": "Consumer Discretionary",
    "DRDB": "Unknown",
    "DRH": "Real Estate",
    "DRIO": "Health Care",
    "DRMA": "Health Care",
    "DRS": "Industrials",
    "DRTS": "Health Care",
    "DRUG": "Health Care",
    "DRVN": "Consumer Discretionary",
    "DSAC": "Finance",
    "DSC": "Technology",
    "DSGN": "Health Care",
    "DSGR": "Consumer Discretionary",
    "DSGX": "Technology",
    "DSP": "Technology",
    "DSWL": "Industrials",
    "DSY": "Consumer Discretionary",
    "DTCX": "Technology",
    "DTI": "Consumer Discretionary",
    "DTIL": "Health Care",
    "DTSQ": "Unknown",
    "DTSS": "Technology",
    "DTST": "Technology",
    "DUKR": "Industrials",
    "DUO": "Finance",
    "DUOL": "Technology",
    "DUOT": "Technology",
    "DVLT": "Consumer Discretionary",
    "DWSN": "Energy",
    "DWTX": "Health Care",
    "DXCM": "Health Care",
    "DXLG": "Consumer Discretionary",
    "DXPE": "Industrials",
    "DXR": "Health Care",
    "DXST": "Industrials",
    "DYAI": "Health Care",
    "DYN": "Health Care",
    "DYNC": "Unknown",
    "DYOR": "Finance",
    "EBAY": "Consumer Discretionary",
    "EBC": "Finance",
    "EBMT": "Finance",
    "EBON": "Finance",
    "ECBK": "Finance",
    "ECHO": "Consumer Discretionary",
    "ECOR": "Health Care",
    "ECPG": "Finance",
    "ECX": "Technology",
    "EDBL": "Consumer Staples",
    "EDHL": "Consumer Discretionary",
    "EDIT": "Health Care",
    "EDRY": "Consumer Discretionary",
    "EDSA": "Health Care",
    "EDTK": "Real Estate",
    "EDUC": "Consumer Discretionary",
    "EEFT": "Finance",
    "EEIQ": "Real Estate",
    "EFOI": "Consumer Discretionary",
    "EFSC": "Finance",
    "EFSI": "Finance",
    "EGAN": "Technology",
    "EGBN": "Finance",
    "EGHA": "Finance",
    "EGHT": "Technology",
    "EH": "Industrials",
    "EHGO": "Consumer Discretionary",
    "EHLD": "Consumer Discretionary",
    "EHTH": "Finance",
    "EIKN": "Health Care",
    "EJH": "Consumer Discretionary",
    "ELAB": "Health Care",
    "ELBM": "Miscellaneous",
    "ELDN": "Health Care",
    "ELE": "Basic Materials",
    "ELMT": "Industrials",
    "ELOG": "Industrials",
    "ELOX": "Health Care",
    "ELPW": "Miscellaneous",
    "ELTK": "Technology",
    "ELTX": "Health Care",
    "ELUT": "Health Care",
    "ELVA": "Miscellaneous",
    "ELVN": "Health Care",
    "ELVR": "Industrials",
    "ELWT": "Consumer Discretionary",
    "EMAT": "Miscellaneous",
    "EMBC": "Health Care",
    "EMIS": "Health Care",
    "EML": "Consumer Discretionary",
    "EMPD": "Industrials",
    "ENGN": "Health Care",
    "ENGS": "Industrials",
    "ENLT": "Utilities",
    "ENLV": "Health Care",
    "ENPH": "Technology",
    "ENRD": "Technology",
    "ENSC": "Health Care",
    "ENSG": "Health Care",
    "ENTA": "Health Care",
    "ENTG": "Industrials",
    "ENTX": "Health Care",
    "ENVB": "Health Care",
    "ENVX": "Miscellaneous",
    "EOCN": "Health Care",
    "EOLS": "Health Care",
    "EOSE": "Miscellaneous",
    "EPOW": "Miscellaneous",
    "EPRX": "Health Care",
    "EPSM": "Consumer Staples",
    "EPSN": "Energy",
    "EQ": "Health Care",
    "EQIX": "Real Estate",
    "EQPT": "Consumer Discretionary",
    "ERAS": "Health Care",
    "ERIC": "Technology",
    "ERIE": "Finance",
    "ERII": "Technology",
    "ERNA": "Health Care",
    "ESCA": "Consumer Discretionary",
    "ESEA": "Consumer Discretionary",
    "ESLA": "Health Care",
    "ESLT": "Industrials",
    "ESOA": "Industrials",
    "ESQ": "Finance",
    "ESTA": "Health Care",
    "ETON": "Health Care",
    "ETOR": "Finance",
    "ETS": "Industrials",
    "EU": "Basic Materials",
    "EUDA": "Health Care",
    "EURK": "Unknown",
    "EVAX": "Health Care",
    "EVCM": "Technology",
    "EVER": "Technology",
    "EVGN": "Industrials",
    "EVGO": "Consumer Discretionary",
    "EVLV": "Technology",
    "EVO": "Health Care",
    "EVOX": "Finance",
    "EVRG": "Utilities",
    "EWAV": "Finance",
    "EWBC": "Finance",
    "EWTX": "Health Care",
    "EXC": "Utilities",
    "EXE": "Energy",
    "EXEL": "Health Care",
    "EXFY": "Technology",
    "EXLS": "Consumer Discretionary",
    "EXOZ": "Health Care",
    "EXPE": "Consumer Discretionary",
    "EXPO": "Consumer Discretionary",
    "EXTR": "Telecommunications",
    "EXYN": "Technology",
    "EYE": "Health Care",
    "EYPT": "Industrials",
    "EZGO": "Consumer Discretionary",
    "EZPW": "Consumer Discretionary",
    "EZRA": "Finance",
    "FA": "Technology",
    "FABC": "Consumer Discretionary",
    "FAC": "Miscellaneous",
    "FACT": "Unknown",
    "FAMI": "Consumer Staples",
    "FANG": "Energy",
    "FAST": "Consumer Discretionary",
    "FATE": "Health Care",
    "FATN": "Technology",
    "FBDT": "Industrials",
    "FBGL": "Consumer Discretionary",
    "FBIO": "Health Care",
    "FBIZ": "Finance",
    "FBLA": "Finance",
    "FBLG": "Health Care",
    "FBNC": "Finance",
    "FBYD": "Consumer Discretionary",
    "FCAP": "Finance",
    "FCBC": "Finance",
    "FCCO": "Finance",
    "FCEL": "Energy",
    "FCFS": "Consumer Discretionary",
    "FCHL": "Consumer Discretionary",
    "FCNCA": "Finance",
    "FCNCP": "Finance",
    "FCUV": "Industrials",
    "FDBC": "Finance",
    "FDMM": "Finance",
    "FDMT": "Health Care",
    "FDSB": "Finance",
    "FDUS": "Finance",
    "FEAM": "Industrials",
    "FEBO": "Consumer Discretionary",
    "FEED": "Health Care",
    "FEIM": "Industrials",
    "FELE": "Consumer Discretionary",
    "FEMY": "Health Care",
    "FENC": "Health Care",
    "FER": "Industrials",
    "FERA": "Unknown",
    "FFAI": "Industrials",
    "FFBC": "Finance",
    "FFIN": "Finance",
    "FFIV": "Telecommunications",
    "FGBI": "Finance",
    "FGI": "Industrials",
    "FGII": "Finance",
    "FGL": "Consumer Discretionary",
    "FGNX": "Finance",
    "FHB": "Finance",
    "FHTX": "Health Care",
    "FIBK": "Finance",
    "FIEE": "Utilities",
    "FIGR": "Finance",
    "FIGX": "Finance",
    "FINW": "Finance",
    "FIP": "Industrials",
    "FISI": "Finance",
    "FISN": "Utilities",
    "FISV": "Consumer Discretionary",
    "FIVE": "Consumer Discretionary",
    "FIVN": "Technology",
    "FIZZ": "Consumer Staples",
    "FKWL": "Utilities",
    "FLD": "Finance",
    "FLEX": "Technology",
    "FLGT": "Health Care",
    "FLL": "Consumer Discretionary",
    "FLNA": "Health Care",
    "FLNC": "Miscellaneous",
    "FLNT": "Consumer Discretionary",
    "FLUX": "Miscellaneous",
    "FLWS": "Consumer Discretionary",
    "FLX": "Industrials",
    "FLXS": "Consumer Discretionary",
    "FLY": "Industrials",
    "FLYE": "Industrials",
    "FLYW": "Consumer Discretionary",
    "FMAC": "Finance",
    "FMAO": "Finance",
    "FMBH": "Finance",
    "FMFC": "Consumer Discretionary",
    "FMNB": "Finance",
    "FMST": "Basic Materials",
    "FNGR": "Technology",
    "FNKO": "Consumer Discretionary",
    "FNLC": "Finance",
    "FNRN": "Finance",
    "FNUC": "Basic Materials",
    "FNWB": "Finance",
    "FNWD": "Finance",
    "FOCL": "Health Care",
    "FOFO": "Consumer Discretionary",
    "FORM": "Technology",
    "FORR": "Industrials",
    "FORTY": "Technology",
    "FOSL": "Consumer Discretionary",
    "FOX": "Industrials",
    "FOXA": "Industrials",
    "FOXF": "Consumer Discretionary",
    "FOXX": "Telecommunications",
    "FRAF": "Finance",
    "FRBA": "Finance",
    "FRBT": "Finance",
    "FRD": "Industrials",
    "FRGT": "Industrials",
    "FRHC": "Finance",
    "FRME": "Finance",
    "FRMEP": "Finance",
    "FRMI": "Real Estate",
    "FRMM": "Finance",
    "FRNM": "Health Care",
    "FROG": "Technology",
    "FRPH": "Finance",
    "FRPT": "Consumer Staples",
    "FRSH": "Technology",
    "FRST": "Finance",
    "FRSX": "Technology",
    "FRTT": "Industrials",
    "FRVO": "Utilities",
    "FSBC": "Finance",
    "FSBW": "Finance",
    "FSEA": "Finance",
    "FSHP": "Unknown",
    "FSLR": "Technology",
    "FSLY": "Technology",
    "FSTR": "Industrials",
    "FSUN": "Finance",
    "FSV": "Finance",
    "FTAI": "Industrials",
    "FTCI": "Technology",
    "FTDR": "Consumer Discretionary",
    "FTEK": "Industrials",
    "FTFT": "Consumer Discretionary",
    "FTH": "Health Care",
    "FTHA": "Finance",
    "FTHM": "Finance",
    "FTLF": "Health Care",
    "FTNT": "Technology",
    "FTRE": "Health Care",
    "FUFU": "Finance",
    "FULC": "Health Care",
    "FULT": "Finance",
    "FUNC": "Finance",
    "FUND": "Finance",
    "FUSB": "Finance",
    "FUSE": "Technology",
    "FUTU": "Finance",
    "FVAV": "Unknown",
    "FVCB": "Finance",
    "FVN": "Unknown",
    "FWAC": "Unknown",
    "FWDI": "Finance",
    "FWONA": "Industrials",
    "FWONK": "Industrials",
    "FWRD": "Industrials",
    "FWRG": "Consumer Discretionary",
    "FXAC": "Finance",
    "FXHO": "Technology",
    "FXNC": "Finance",
    "GABC": "Finance",
    "GAIA": "Consumer Discretionary",
    "GAIN": "Finance",
    "GALT": "Health Care",
    "GAME": "Consumer Discretionary",
    "GANX": "Health Care",
    "GASS": "Consumer Discretionary",
    "GAUZ": "Miscellaneous",
    "GBDC": "Finance",
    "GBFH": "Finance",
    "GBLI": "Finance",
    "GCBC": "Finance",
    "GCGR": "Unknown",
    "GCL": "Technology",
    "GCMG": "Finance",
    "GCT": "Consumer Discretionary",
    "GCTK": "Health Care",
    "GDC": "Industrials",
    "GDEV": "Technology",
    "GDHG": "Consumer Discretionary",
    "GDRX": "Technology",
    "GDS": "Technology",
    "GDTC": "Health Care",
    "GDYN": "Technology",
    "GECC": "Finance",
    "GEG": "Technology",
    "GEHC": "Health Care",
    "GELS": "Health Care",
    "GEMI": "Finance",
    "GEN": "Technology",
    "GENB": "Health Care",
    "GENK": "Consumer Discretionary",
    "GEOS": "Industrials",
    "GERN": "Health Care",
    "GEVO": "Industrials",
    "GFAI": "Consumer Discretionary",
    "GFS": "Technology",
    "GFUZ": "Utilities",
    "GGAL": "Finance",
    "GGR": "Industrials",
    "GH": "Health Care",
    "GHRS": "Health Care",
    "GHXI": "Unknown",
    "GIBO": "Technology",
    "GIFT": "Consumer Discretionary",
    "GIGM": "Technology",
    "GIII": "Consumer Discretionary",
    "GILD": "Health Care",
    "GILT": "Technology",
    "GIPR": "Real Estate",
    "GITS": "Technology",
    "GIW": "Finance",
    "GIX": "Finance",
    "GIXI": "Technology",
    "GLAD": "Consumer Discretionary",
    "GLBE": "Technology",
    "GLBS": "Consumer Discretionary",
    "GLE": "Technology",
    "GLIBA": "Telecommunications",
    "GLIBK": "Telecommunications",
    "GLND": "Energy",
    "GLNG": "Consumer Discretionary",
    "GLOO": "Technology",
    "GLPI": "Real Estate",
    "GLRE": "Finance",
    "GLSI": "Health Care",
    "GLUE": "Health Care",
    "GLXG": "Industrials",
    "GLXY": "Finance",
    "GMAB": "Health Care",
    "GMEX": "Consumer Discretionary",
    "GMHS": "Technology",
    "GMM": "Technology",
    "GNLN": "Consumer Discretionary",
    "GNLX": "Health Care",
    "GNPX": "Health Care",
    "GNSS": "Consumer Staples",
    "GNTA": "Health Care",
    "GNTX": "Consumer Discretionary",
    "GO": "Consumer Staples",
    "GOAI": "Technology",
    "GOGO": "Consumer Discretionary",
    "GOOD": "Real Estate",
    "GOOG": "Technology",
    "GOOGL": "Technology",
    "GOSS": "Health Care",
    "GOVX": "Health Care",
    "GP": "Consumer Discretionary",
    "GPAC": "Unknown",
    "GPAT": "Unknown",
    "GPCR": "Health Care",
    "GPRE": "Industrials",
    "GPRO": "Consumer Discretionary",
    "GRAB": "Consumer Discretionary",
    "GRAL": "Health Care",
    "GRAN": "Finance",
    "GRCE": "Health Care",
    "GRDX": "Health Care",
    "GRFS": "Health Care",
    "GRI": "Health Care",
    "GRML": "Health Care",
    "GRNQ": "Consumer Discretionary",
    "GROW": "Finance",
    "GRPN": "Consumer Discretionary",
    "GRRR": "Technology",
    "GRSD": "Consumer Discretionary",
    "GRVY": "Technology",
    "GRWG": "Consumer Discretionary",
    "GSAT": "Consumer Discretionary",
    "GSBC": "Finance",
    "GSHD": "Finance",
    "GSHR": "Unknown",
    "GSIT": "Technology",
    "GSIW": "Finance",
    "GSM": "Basic Materials",
    "GSRF": "Unknown",
    "GSRV": "Finance",
    "GSUN": "Real Estate",
    "GT": "Consumer Discretionary",
    "GTBP": "Health Care",
    "GTEC": "Industrials",
    "GTEN": "Unknown",
    "GTERA": "Finance",
    "GTIM": "Consumer Discretionary",
    "GTLB": "Technology",
    "GTM": "Technology",
    "GTX": "Consumer Discretionary",
    "GUAC": "Finance",
    "GURE": "Industrials",
    "GUTS": "Health Care",
    "GVH": "Industrials",
    "GWAV": "Industrials",
    "GWRS": "Utilities",
    "GXAI": "Technology",
    "GYGY": "Technology",
    "GYRE": "Health Care",
    "GYRO": "Real Estate",
    "HACQ": "Finance",
    "HAFC": "Finance",
    "HAIN": "Consumer Staples",
    "HALO": "Health Care",
    "HAO": "Consumer Discretionary",
    "HAPN": "Finance",
    "HAS": "Consumer Discretionary",
    "HAVA": "Unknown",
    "HBAN": "Finance",
    "HBCP": "Finance",
    "HBIO": "Industrials",
    "HBNB": "Consumer Discretionary",
    "HBNC": "Finance",
    "HBT": "Finance",
    "HCAC": "Consumer Discretionary",
    "HCAI": "Consumer Discretionary",
    "HCAT": "Technology",
    "HCIC": "Unknown",
    "HCKT": "Consumer Discretionary",
    "HCM": "Health Care",
    "HCMA": "Consumer Discretionary",
    "HCSG": "Health Care",
    "HCTI": "Technology",
    "HCWB": "Health Care",
    "HDL": "Consumer Discretionary",
    "HDRN": "Utilities",
    "HDSN": "Consumer Discretionary",
    "HELE": "Consumer Discretionary",
    "HELP": "Health Care",
    "HEPS": "Consumer Discretionary",
    "HERE": "Consumer Discretionary",
    "HERZ": "Finance",
    "HFBL": "Finance",
    "HFFG": "Consumer Discretionary",
    "HFWA": "Finance",
    "HGBL": "Consumer Discretionary",
    "HHS": "Consumer Discretionary",
    "HIFS": "Finance",
    "HIHO": "Industrials",
    "HIMX": "Technology",
    "HIND": "Health Care",
    "HIT": "Finance",
    "HITI": "Consumer Discretionary",
    "HIVE": "Finance",
    "HKIT": "Technology",
    "HKPD": "Health Care",
    "HLIT": "Technology",
    "HLMN": "Consumer Discretionary",
    "HLNE": "Finance",
    "HLP": "Industrials",
    "HLXC": "Unknown",
    "HMH": "Consumer Discretionary",
    "HMR": "Consumer Discretionary",
    "HNNA": "Finance",
    "HNRG": "Utilities",
    "HNST": "Consumer Discretionary",
    "HNVR": "Finance",
    "HODO": "Finance",
    "HOFT": "Consumer Discretionary",
    "HOLO": "Technology",
    "HON": "Industrials",
    "HONA": "Industrials",
    "HOOD": "Finance",
    "HOPE": "Finance",
    "HOUR": "Consumer Discretionary",
    "HOVNP": "Consumer Discretionary",
    "HOVR": "Industrials",
    "HOWL": "Health Care",
    "HPAI": "Technology",
    "HPK": "Energy",
    "HQ": "Technology",
    "HQI": "Consumer Discretionary",
    "HQY": "Consumer Discretionary",
    "HRMY": "Health Care",
    "HROW": "Health Care",
    "HRTX": "Health Care",
    "HRZN": "Finance",
    "HSAI": "Industrials",
    "HSCS": "Health Care",
    "HSDT": "Health Care",
    "HSIC": "Health Care",
    "HST": "Real Estate",
    "HSTM": "Technology",
    "HTCO": "Consumer Discretionary",
    "HTCR": "Technology",
    "HTFL": "Health Care",
    "HTHT": "Consumer Discretionary",
    "HTLD": "Industrials",
    "HTLM": "Consumer Discretionary",
    "HTO": "Utilities",
    "HTOO": "Technology",
    "HTZ": "Consumer Discretionary",
    "HUBC": "Telecommunications",
    "HUBG": "Industrials",
    "HUDI": "Industrials",
    "HUHU": "Telecommunications",
    "HUIZ": "Finance",
    "HUMA": "Health Care",
    "HURA": "Health Care",
    "HURC": "Industrials",
    "HURN": "Consumer Discretionary",
    "HUT": "Finance",
    "HVII": "Unknown",
    "HVMC": "Unknown",
    "HWBK": "Finance",
    "HWC": "Finance",
    "HWH": "Health Care",
    "HWKN": "Consumer Discretionary",
    "HXHX": "Industrials",
    "HYFM": "Consumer Discretionary",
    "HYFT": "Health Care",
    "HYMC": "Basic Materials",
    "HYNE": "Finance",
    "HYPD": "Health Care",
    "HYPR": "Health Care",
    "IA": "Technology",
    "IACO": "Finance",
    "IACQ": "Finance",
    "IART": "Health Care",
    "IBAC": "Finance",
    "IBCP": "Finance",
    "IBEX": "Technology",
    "IBG": "Consumer Staples",
    "IBIO": "Health Care",
    "IBKR": "Finance",
    "IBOC": "Finance",
    "IBRX": "Health Care",
    "ICCC": "Health Care",
    "ICCM": "Health Care",
    "ICFI": "Consumer Discretionary",
    "ICG": "Technology",
    "ICHR": "Technology",
    "ICLR": "Health Care",
    "ICMB": "Finance",
    "ICON": "Consumer Discretionary",
    "ICU": "Health Care",
    "ICUI": "Health Care",
    "IDAC": "Unknown",
    "IDAI": "Technology",
    "IDCC": "Miscellaneous",
    "IDN": "Technology",
    "IDXX": "Health Care",
    "IDYA": "Health Care",
    "IEAG": "Finance",
    "IEP": "Energy",
    "IESC": "Industrials",
    "IFBD": "Technology",
    "IFRX": "Health Care",
    "IGAC": "Finance",
    "IGIC": "Finance",
    "IHRT": "Consumer Discretionary",
    "III": "Consumer Discretionary",
    "IIIV": "Technology",
    "IKT": "Health Care",
    "ILAG": "Consumer Discretionary",
    "ILLR": "Finance",
    "ILLU": "Finance",
    "ILMN": "Health Care",
    "ILPT": "Real Estate",
    "IMA": "Health Care",
    "IMCC": "Health Care",
    "IMCR": "Health Care",
    "IMDX": "Health Care",
    "IMKTA": "Consumer Staples",
    "IMMP": "Health Care",
    "IMMR": "Technology",
    "IMMX": "Health Care",
    "IMNM": "Health Care",
    "IMNN": "Health Care",
    "IMOS": "Technology",
    "IMPP": "Consumer Discretionary",
    "IMRN": "Health Care",
    "IMRX": "Health Care",
    "IMSR": "Industrials",
    "IMTE": "Consumer Staples",
    "IMTX": "Health Care",
    "IMUX": "Health Care",
    "IMVT": "Health Care",
    "IMXI": "Consumer Discretionary",
    "INAB": "Health Care",
    "INAC": "Unknown",
    "INBK": "Finance",
    "INBS": "Health Care",
    "INBX": "Health Care",
    "INCR": "Health Care",
    "INCY": "Health Care",
    "INDB": "Finance",
    "INDI": "Technology",
    "INDP": "Health Care",
    "INDV": "Health Care",
    "INEO": "Consumer Discretionary",
    "INGN": "Health Care",
    "INHD": "Industrials",
    "INIO": "Consumer Discretionary",
    "INKT": "Health Care",
    "INLF": "Industrials",
    "INM": "Health Care",
    "INMB": "Health Care",
    "INMD": "Health Care",
    "INNV": "Health Care",
    "INO": "Health Care",
    "INOD": "Technology",
    "INSE": "Technology",
    "INSG": "Telecommunications",
    "INSM": "Health Care",
    "INTA": "Technology",
    "INTC": "Technology",
    "INTG": "Real Estate",
    "INTJ": "Consumer Discretionary",
    "INTR": "Finance",
    "INTS": "Health Care",
    "INTU": "Technology",
    "INTZ": "Telecommunications",
    "INV": "Finance",
    "INVA": "Health Care",
    "INVE": "Technology",
    "INVZ": "Consumer Discretionary",
    "IOND": "Finance",
    "IONR": "Industrials",
    "IONS": "Health Care",
    "IOSP": "Industrials",
    "IOTR": "Consumer Discretionary",
    "IOVA": "Health Care",
    "IPAR": "Consumer Discretionary",
    "IPDN": "Technology",
    "IPEX": "Health Care",
    "IPFX": "Finance",
    "IPGP": "Technology",
    "IPHA": "Health Care",
    "IPM": "Technology",
    "IPSC": "Health Care",
    "IPST": "Consumer Staples",
    "IPVV": "Finance",
    "IPW": "Consumer Discretionary",
    "IPWR": "Technology",
    "IPX": "Basic Materials",
    "IPXG": "Finance",
    "IQ": "Consumer Discretionary",
    "IQMX": "Technology",
    "IQST": "Telecommunications",
    "IRD": "Health Care",
    "IRDM": "Consumer Discretionary",
    "IREN": "Finance",
    "IRHO": "Finance",
    "IRIX": "Health Care",
    "IRMD": "Health Care",
    "IRON": "Health Care",
    "IRTC": "Health Care",
    "IRWD": "Health Care",
    "ISBA": "Finance",
    "ISNR": "Finance",
    "ISPC": "Health Care",
    "ISPR": "Health Care",
    "ISRG": "Health Care",
    "ISTR": "Finance",
    "ITG": "Industrials",
    "ITHA": "Unknown",
    "ITIC": "Finance",
    "ITOC": "Health Care",
    "ITRI": "Industrials",
    "ITRN": "Technology",
    "IVA": "Health Care",
    "IVDA": "Technology",
    "IVF": "Health Care",
    "IVVD": "Health Care",
    "IXHL": "Health Care",
    "IZEA": "Consumer Discretionary",
    "IZM": "Consumer Discretionary",
    "JACK": "Consumer Discretionary",
    "JAGX": "Health Care",
    "JAKK": "Consumer Discretionary",
    "JANX": "Health Care",
    "JATT": "Finance",
    "JAZZ": "Health Care",
    "JBDI": "Unknown",
    "JBHT": "Industrials",
    "JBIO": "Health Care",
    "JBLU": "Consumer Discretionary",
    "JBSS": "Consumer Staples",
    "JCAP": "Finance",
    "JCSE": "Consumer Discretionary",
    "JCTC": "Consumer Discretionary",
    "JD": "Consumer Discretionary",
    "JDZG": "Real Estate",
    "JEM": "Consumer Discretionary",
    "JF": "Technology",
    "JFIN": "Finance",
    "JFU": "Finance",
    "JG": "Technology",
    "JJSF": "Consumer Staples",
    "JKHY": "Technology",
    "JL": "Consumer Discretionary",
    "JLHL": "Consumer Discretionary",
    "JMSB": "Finance",
    "JONE": "Finance",
    "JOUT": "Consumer Discretionary",
    "JOYY": "Technology",
    "JRSH": "Consumer Discretionary",
    "JRVR": "Finance",
    "JSPR": "Health Care",
    "JTAI": "Consumer Discretionary",
    "JTTT": "Finance",
    "JUNS": "Health Care",
    "JVA": "Consumer Staples",
    "JWEL": "Consumer Discretionary",
    "JXG": "Industrials",
    "JYD": "Industrials",
    "JYNT": "Miscellaneous",
    "JZ": "Real Estate",
    "JZXN": "Consumer Discretionary",
    "KALA": "Health Care",
    "KALU": "Industrials",
    "KARD": "Health Care",
    "KARO": "Technology",
    "KAZR": "Consumer Discretionary",
    "KBON": "Finance",
    "KBSX": "Consumer Discretionary",
    "KC": "Technology",
    "KCHV": "Unknown",
    "KDK": "Technology",
    "KDP": "Consumer Staples",
    "KE": "Technology",
    "KEEL": "Finance",
    "KELYA": "Consumer Discretionary",
    "KELYB": "Consumer Discretionary",
    "KEQU": "Industrials",
    "KEYY": "Finance",
    "KFFB": "Finance",
    "KFII": "Unknown",
    "KG": "Finance",
    "KGEI": "Energy",
    "KIDS": "Health Care",
    "KIDZ": "Real Estate",
    "KINS": "Finance",
    "KITT": "Industrials",
    "KLAC": "Technology",
    "KLIC": "Technology",
    "KLRA": "Health Care",
    "KLRS": "Health Care",
    "KLTR": "Technology",
    "KLXE": "Energy",
    "KMB": "Consumer Discretionary",
    "KMDA": "Health Care",
    "KMRK": "Consumer Discretionary",
    "KMTS": "Health Care",
    "KNDI": "Industrials",
    "KNSA": "Health Care",
    "KOD": "Health Care",
    "KOPN": "Technology",
    "KOSS": "Consumer Staples",
    "KOYN": "Unknown",
    "KPLT": "Consumer Discretionary",
    "KPRX": "Health Care",
    "KPTI": "Health Care",
    "KRAQ": "Unknown",
    "KRKR": "Consumer Discretionary",
    "KRMD": "Health Care",
    "KRNT": "Industrials",
    "KRNY": "Finance",
    "KROS": "Health Care",
    "KRRO": "Health Care",
    "KRSA": "Health Care",
    "KRT": "Industrials",
    "KRUS": "Consumer Discretionary",
    "KRYS": "Health Care",
    "KSCP": "Telecommunications",
    "KSPI": "Unknown",
    "KTCC": "Technology",
    "KTOS": "Industrials",
    "KTTA": "Health Care",
    "KTWO": "Health Care",
    "KURA": "Health Care",
    "KUST": "Technology",
    "KVHI": "Consumer Discretionary",
    "KXIN": "Consumer Discretionary",
    "KYIV": "Telecommunications",
    "KYMR": "Health Care",
    "KYNB": "Health Care",
    "KYTX": "Health Care",
    "KZIA": "Health Care",
    "LAB": "Industrials",
    "LABT": "Health Care",
    "LAES": "Technology",
    "LAFA": "Unknown",
    "LAKE": "Health Care",
    "LAMR": "Real Estate",
    "LAND": "Real Estate",
    "LARK": "Finance",
    "LASE": "Miscellaneous",
    "LASR": "Technology",
    "LATA": "Finance",
    "LAUR": "Real Estate",
    "LBGJ": "Industrials",
    "LBRX": "Health Care",
    "LBTYA": "Telecommunications",
    "LBTYB": "Telecommunications",
    "LBTYK": "Telecommunications",
    "LCCC": "Finance",
    "LCFY": "Technology",
    "LCID": "Industrials",
    "LCNB": "Finance",
    "LCUT": "Consumer Discretionary",
    "LE": "Consumer Discretionary",
    "LECO": "Industrials",
    "LEDS": "Technology",
    "LEE": "Consumer Discretionary",
    "LEGH": "Consumer Discretionary",
    "LEGN": "Health Care",
    "LENZ": "Health Care",
    "LESL": "Consumer Discretionary",
    "LEXX": "Health Care",
    "LFAC": "Finance",
    "LFCR": "Health Care",
    "LFMD": "Health Care",
    "LFS": "Real Estate",
    "LFST": "Health Care",
    "LFTO": "Technology",
    "LFUS": "Energy",
    "LFVN": "Health Care",
    "LFWD": "Health Care",
    "LGCL": "Technology",
    "LGHL": "Finance",
    "LGIH": "Consumer Discretionary",
    "LGN": "Consumer Discretionary",
    "LGND": "Health Care",
    "LGO": "Industrials",
    "LGVN": "Health Care",
    "LHAI": "Finance",
    "LHSW": "Technology",
    "LI": "Industrials",
    "LICN": "Consumer Discretionary",
    "LIDR": "Consumer Discretionary",
    "LIEN": "Finance",
    "LIF": "Technology",
    "LIFE": "Finance",
    "LILA": "Telecommunications",
    "LILAK": "Telecommunications",
    "LILAP": "Telecommunications",
    "LIME": "Technology",
    "LIMN": "Health Care",
    "LIN": "Basic Materials",
    "LINC": "Real Estate",
    "LIND": "Consumer Discretionary",
    "LINE": "Real Estate",
    "LINK": "Technology",
    "LIQT": "Technology",
    "LITE": "Telecommunications",
    "LITS": "Health Care",
    "LIVE": "Consumer Discretionary",
    "LIVN": "Health Care",
    "LKFN": "Finance",
    "LKFT": "Health Care",
    "LKQ": "Consumer Discretionary",
    "LKSP": "Unknown",
    "LLYVA": "Consumer Discretionary",
    "LLYVK": "Consumer Discretionary",
    "LMAT": "Health Care",
    "LMB": "Consumer Discretionary",
    "LMNR": "Consumer Staples",
    "LMRI": "Health Care",
    "LNAI": "Health Care",
    "LNKS": "Technology",
    "LNSR": "Health Care",
    "LNT": "Utilities",
    "LNTH": "Health Care",
    "LNZA": "Industrials",
    "LOAN": "Real Estate",
    "LOBO": "Consumer Discretionary",
    "LOCO": "Consumer Discretionary",
    "LOGI": "Technology",
    "LONA": "Health Care",
    "LOOP": "Industrials",
    "LOPE": "Real Estate",
    "LOT": "Industrials",
    "LOVE": "Consumer Discretionary",
    "LPAA": "Unknown",
    "LPBB": "Unknown",
    "LPCN": "Health Care",
    "LPCV": "Unknown",
    "LPLA": "Finance",
    "LPTH": "Technology",
    "LQDA": "Health Care",
    "LQDT": "Consumer Discretionary",
    "LRCX": "Technology",
    "LRE": "Consumer Discretionary",
    "LRHC": "Finance",
    "LRMR": "Health Care",
    "LSAK": "Finance",
    "LSBK": "Finance",
    "LSCC": "Technology",
    "LSE": "Consumer Discretionary",
    "LSTA": "Health Care",
    "LSTR": "Industrials",
    "LTBR": "Basic Materials",
    "LTGO": "Health Care",
    "LTGR": "Finance",
    "LTRN": "Health Care",
    "LTRX": "Telecommunications",
    "LUCD": "Health Care",
    "LUCY": "Health Care",
    "LULU": "Consumer Discretionary",
    "LUNG": "Health Care",
    "LUNR": "Industrials",
    "LVLU": "Consumer Discretionary",
    "LVO": "Consumer Discretionary",
    "LWAC": "Finance",
    "LWAY": "Consumer Staples",
    "LWLG": "Industrials",
    "LX": "Finance",
    "LXEH": "Real Estate",
    "LXEO": "Health Care",
    "LXRX": "Health Care",
    "LYEL": "Health Care",
    "LYFT": "Consumer Discretionary",
    "LYTS": "Consumer Discretionary",
    "LZ": "Technology",
    "LZMH": "Technology",
    "MAAS": "Finance",
    "MACI": "Unknown",
    "MAKO": "Basic Materials",
    "MAMA": "Consumer Staples",
    "MAMO": "Consumer Discretionary",
    "MANH": "Technology",
    "MAR": "Consumer Discretionary",
    "MARA": "Finance",
    "MASK": "Technology",
    "MASS": "Industrials",
    "MAT": "Consumer Discretionary",
    "MATH": "Finance",
    "MATW": "Telecommunications",
    "MAYS": "Real Estate",
    "MAZE": "Health Care",
    "MB": "Consumer Discretionary",
    "MBAI": "Health Care",
    "MBBC": "Finance",
    "MBIN": "Finance",
    "MBIO": "Health Care",
    "MBLY": "Technology",
    "MBOT": "Health Care",
    "MBRX": "Health Care",
    "MBUU": "Industrials",
    "MBVI": "Unknown",
    "MBWM": "Finance",
    "MBX": "Health Care",
    "MCAH": "Finance",
    "MCBS": "Finance",
    "MCFT": "Industrials",
    "MCGA": "Utilities",
    "MCHB": "Finance",
    "MCHP": "Technology",
    "MCHX": "Technology",
    "MCRB": "Health Care",
    "MCRI": "Consumer Discretionary",
    "MDAI": "Health Care",
    "MDB": "Technology",
    "MDBH": "Finance",
    "MDCX": "Health Care",
    "MDGL": "Health Care",
    "MDIA": "Consumer Discretionary",
    "MDLN": "Health Care",
    "MDLZ": "Consumer Staples",
    "MDRR": "Real Estate",
    "MDWD": "Health Care",
    "MDXG": "Health Care",
    "MDXH": "Health Care",
    "MEDP": "Health Care",
    "MEDS": "Health Care",
    "MEGL": "Finance",
    "MELI": "Consumer Discretionary",
    "MENS": "Health Care",
    "MEOH": "Industrials",
    "MERC": "Basic Materials",
    "MESH": "Unknown",
    "MESO": "Health Care",
    "META": "Technology",
    "METC": "Energy",
    "METCB": "Energy",
    "MEVO": "Finance",
    "MF": "Technology",
    "MFI": "Technology",
    "MFIC": "Finance",
    "MFIN": "Finance",
    "MFP": "Industrials",
    "MGEE": "Energy",
    "MGIH": "Consumer Discretionary",
    "MGN": "Consumer Staples",
    "MGNI": "Technology",
    "MGNX": "Health Care",
    "MGPI": "Consumer Staples",
    "MGRC": "Consumer Discretionary",
    "MGRT": "Technology",
    "MGRX": "Health Care",
    "MGTX": "Health Care",
    "MGX": "Health Care",
    "MGYR": "Finance",
    "MIAC": "Unknown",
    "MIDD": "Industrials",
    "MIMI": "Consumer Discretionary",
    "MIND": "Industrials",
    "MIRA": "Health Care",
    "MIRM": "Health Care",
    "MIST": "Health Care",
    "MITK": "Technology",
    "MKDW": "Technology",
    "MKLY": "Finance",
    "MKSI": "Industrials",
    "MKTW": "Technology",
    "MKTX": "Finance",
    "MKZR": "Real Estate",
    "MLAA": "Finance",
    "MLAB": "Industrials",
    "MLCI": "Finance",
    "MLCO": "Consumer Discretionary",
    "MLEC": "Finance",
    "MLGO": "Technology",
    "MLKN": "Consumer Discretionary",
    "MLTX": "Health Care",
    "MLYS": "Health Care",
    "MMED": "Health Care",
    "MMLP": "Energy",
    "MMSI": "Health Care",
    "MMTX": "Finance",
    "MMYT": "Consumer Discretionary",
    "MNDO": "Technology",
    "MNDR": "Technology",
    "MNDY": "Technology",
    "MNKD": "Health Care",
    "MNOV": "Health Care",
    "MNPR": "Health Care",
    "MNRO": "Consumer Discretionary",
    "MNSB": "Finance",
    "MNSBP": "Finance",
    "MNST": "Consumer Staples",
    "MNTK": "Utilities",
    "MNTS": "Industrials",
    "MNY": "Consumer Discretionary",
    "MOB": "Industrials",
    "MOBI": "Health Care",
    "MOBX": "Technology",
    "MODD": "Health Care",
    "MOLN": "Health Care",
    "MOMO": "Technology",
    "MORN": "Finance",
    "MOVE": "Technology",
    "MPAA": "Consumer Discretionary",
    "MPB": "Finance",
    "MPLT": "Health Care",
    "MPWR": "Technology",
    "MQ": "Technology",
    "MRAM": "Technology",
    "MRBK": "Finance",
    "MRCO": "Finance",
    "MRCY": "Technology",
    "MRDN": "Technology",
    "MREO": "Health Care",
    "MRKR": "Health Care",
    "MRLN": "Technology",
    "MRM": "Consumer Discretionary",
    "MRNA": "Health Care",
    "MRNO": "Consumer Discretionary",
    "MRTN": "Industrials",
    "MRVI": "Health Care",
    "MRVL": "Technology",
    "MRX": "Finance",
    "MSAI": "Technology",
    "MSBI": "Finance",
    "MSEX": "Utilities",
    "MSFT": "Technology",
    "MSGM": "Technology",
    "MSGY": "Consumer Discretionary",
    "MSLE": "Health Care",
    "MSS": "Consumer Staples",
    "MSTR": "Technology",
    "MTC": "Technology",
    "MTCH": "Technology",
    "MTEK": "Telecommunications",
    "MTEN": "Industrials",
    "MTEX": "Health Care",
    "MTLS": "Technology",
    "MTRX": "Consumer Discretionary",
    "MTSI": "Technology",
    "MTVA": "Health Care",
    "MU": "Technology",
    "MUZE": "Finance",
    "MVBF": "Finance",
    "MVIS": "Technology",
    "MVST": "Miscellaneous",
    "MWC": "Technology",
    "MWH": "Industrials",
    "MWYN": "Consumer Discretionary",
    "MXCT": "Health Care",
    "MXL": "Technology",
    "MYFW": "Finance",
    "MYGN": "Health Care",
    "MYPS": "Technology",
    "MYRG": "Industrials",
    "MYSE": "Telecommunications",
    "MYSZ": "Technology",
    "MYX": "Finance",
    "MZTI": "Consumer Staples",
    "NA": "Technology",
    "NAAS": "Consumer Discretionary",
    "NAGE": "Health Care",
    "NAII": "Health Care",
    "NAKA": "Health Care",
    "NAMI": "Real Estate",
    "NAMM": "Basic Materials",
    "NAMS": "Health Care",
    "NATH": "Consumer Discretionary",
    "NATR": "Health Care",
    "NAUT": "Industrials",
    "NAVI": "Finance",
    "NAVN": "Technology",
    "NB": "Basic Materials",
    "NBBK": "Finance",
    "NBIS": "Technology",
    "NBIX": "Health Care",
    "NBN": "Finance",
    "NBP": "Health Care",
    "NBRG": "Finance",
    "NBTB": "Finance",
    "NBTX": "Health Care",
    "NCEL": "Health Care",
    "NCEW": "Industrials",
    "NCI": "Consumer Discretionary",
    "NCMI": "Consumer Discretionary",
    "NCNA": "Health Care",
    "NCNO": "Technology",
    "NCO": "Unknown",
    "NCPL": "Finance",
    "NCRA": "Consumer Staples",
    "NCT": "Consumer Discretionary",
    "NCTY": "Finance",
    "NDAQ": "Finance",
    "NDLS": "Consumer Discretionary",
    "NDRA": "Health Care",
    "NDSN": "Industrials",
    "NECB": "Finance",
    "NEGG": "Consumer Discretionary",
    "NEO": "Health Care",
    "NEOG": "Health Care",
    "NEON": "Technology",
    "NEOV": "Miscellaneous",
    "NEPH": "Health Care",
    "NERV": "Health Care",
    "NESR": "Energy",
    "NEUP": "Health Care",
    "NEWT": "Finance",
    "NEXM": "Basic Materials",
    "NEXN": "Technology",
    "NEXR": "Consumer Discretionary",
    "NEXT": "Utilities",
    "NFE": "Utilities",
    "NFLX": "Consumer Discretionary",
    "NGEN": "Health Care",
    "NGNE": "Health Care",
    "NHIC": "Unknown",
    "NHIV": "Finance",
    "NHP": "Real Estate",
    "NHTC": "Consumer Discretionary",
    "NICE": "Technology",
    "NICM": "Basic Materials",
    "NIKI": "Industrials",
    "NIPG": "Consumer Discretionary",
    "NIU": "Industrials",
    "NIVF": "Health Care",
    "NIXX": "Technology",
    "NKLR": "Industrials",
    "NKSH": "Finance",
    "NKTR": "Health Care",
    "NKTX": "Health Care",
    "NMAD": "Health Care",
    "NMFC": "Finance",
    "NMIH": "Finance",
    "NMP": "Finance",
    "NMRA": "Health Care",
    "NMRK": "Finance",
    "NMTC": "Health Care",
    "NN": "Industrials",
    "NNBR": "Industrials",
    "NNDM": "Technology",
    "NNE": "Utilities",
    "NNNN": "Health Care",
    "NNOX": "Health Care",
    "NODK": "Finance",
    "NOEM": "Unknown",
    "NOMA": "Consumer Discretionary",
    "NOVT": "Miscellaneous",
    "NPAC": "Finance",
    "NPCE": "Health Care",
    "NPT": "Consumer Discretionary",
    "NRC": "Health Care",
    "NRDS": "Technology",
    "NRIM": "Finance",
    "NRIX": "Health Care",
    "NRSN": "Health Care",
    "NRXP": "Health Care",
    "NSAI": "Unknown",
    "NSIT": "Consumer Discretionary",
    "NSLR": "Finance",
    "NSPR": "Health Care",
    "NSSC": "Telecommunications",
    "NSTS": "Finance",
    "NSYS": "Technology",
    "NTAP": "Technology",
    "NTCL": "Technology",
    "NTCT": "Technology",
    "NTES": "Technology",
    "NTGR": "Utilities",
    "NTHI": "Health Care",
    "NTIC": "Industrials",
    "NTLA": "Health Care",
    "NTNX": "Technology",
    "NTRA": "Health Care",
    "NTRB": "Health Care",
    "NTRP": "Consumer Discretionary",
    "NTRS": "Finance",
    "NTSK": "Technology",
    "NTWK": "Technology",
    "NTWO": "Unknown",
    "NUAI": "Energy",
    "NUCL": "Basic Materials",
    "NUR": "Unknown",
    "NUTX": "Consumer Discretionary",
    "NUWE": "Health Care",
    "NVAX": "Health Care",
    "NVCR": "Health Care",
    "NVCT": "Health Care",
    "NVDA": "Technology",
    "NVEC": "Technology",
    "NVMI": "Technology",
    "NVNI": "Technology",
    "NVNO": "Health Care",
    "NVTS": "Technology",
    "NVX": "Miscellaneous",
    "NWBI": "Finance",
    "NWE": "Utilities",
    "NWFL": "Finance",
    "NWGL": "Basic Materials",
    "NWL": "Industrials",
    "NWPX": "Industrials",
    "NWS": "Consumer Discretionary",
    "NWSA": "Consumer Discretionary",
    "NWTG": "Consumer Discretionary",
    "NXAT": "Consumer Discretionary",
    "NXGL": "Health Care",
    "NXH": "Consumer Discretionary",
    "NXL": "Health Care",
    "NXPI": "Technology",
    "NXPL": "Telecommunications",
    "NXST": "Industrials",
    "NXT": "Technology",
    "NXTC": "Health Care",
    "NXTS": "Industrials",
    "NXTT": "Technology",
    "NXXT": "Consumer Discretionary",
    "NYAX": "Technology",
    "NYXH": "Health Care",
    "OABI": "Health Care",
    "OACC": "Finance",
    "OBA": "Finance",
    "OBAI": "Consumer Discretionary",
    "OBIO": "Health Care",
    "OBT": "Finance",
    "OBX": "Health Care",
    "OCC": "Industrials",
    "OCCI": "Finance",
    "OCFC": "Finance",
    "OCG": "Consumer Discretionary",
    "OCGN": "Health Care",
    "OCLT": "Finance",
    "OCS": "Health Care",
    "OCSL": "Finance",
    "OCTV": "Technology",
    "OCUL": "Health Care",
    "ODD": "Consumer Discretionary",
    "ODFL": "Industrials",
    "ODTX": "Health Care",
    "ODYS": "Technology",
    "OESX": "Consumer Discretionary",
    "OFAL": "Consumer Discretionary",
    "OFIX": "Health Care",
    "OFLX": "Industrials",
    "OFS": "Finance",
    "OGI": "Health Care",
    "OHAC": "Unknown",
    "OIM": "Unknown",
    "OIO": "Utilities",
    "OKTA": "Technology",
    "OKUR": "Health Care",
    "OKYO": "Health Care",
    "OLB": "Consumer Discretionary",
    "OLED": "Technology",
    "OLLI": "Consumer Discretionary",
    "OLMA": "Health Care",
    "OLOX": "Consumer Discretionary",
    "OM": "Health Care",
    "OMAB": "Consumer Discretionary",
    "OMCL": "Technology",
    "OMDA": "Health Care",
    "OMER": "Health Care",
    "OMEX": "Consumer Discretionary",
    "OMH": "Finance",
    "OMSE": "Consumer Discretionary",
    "ON": "Technology",
    "ONB": "Finance",
    "ONC": "Health Care",
    "ONCH": "Unknown",
    "ONCO": "Health Care",
    "ONCY": "Health Care",
    "ONDS": "Technology",
    "ONEG": "Consumer Discretionary",
    "ONEW": "Consumer Discretionary",
    "ONFO": "Technology",
    "ONMD": "Health Care",
    "OPAD": "Finance",
    "OPAL": "Utilities",
    "OPBK": "Finance",
    "OPCH": "Health Care",
    "OPEN": "Finance",
    "OPI": "Finance",
    "OPK": "Health Care",
    "OPRA": "Technology",
    "OPRT": "Finance",
    "OPRX": "Consumer Discretionary",
    "OPTH": "Health Care",
    "OPTX": "Technology",
    "OPXS": "Technology",
    "ORBS": "Finance",
    "ORGO": "Health Care",
    "ORIC": "Health Care",
    "ORIO": "Finance",
    "ORIQ": "Unknown",
    "ORKA": "Health Care",
    "ORKT": "Technology",
    "ORLY": "Consumer Discretionary",
    "ORMP": "Health Care",
    "ORRF": "Finance",
    "OSBC": "Finance",
    "OSIS": "Technology",
    "OSPN": "Technology",
    "OSPR": "Finance",
    "OSS": "Technology",
    "OSUR": "Health Care",
    "OSW": "Consumer Discretionary",
    "OTEX": "Technology",
    "OTGA": "Finance",
    "OTLK": "Health Care",
    "OTLY": "Consumer Staples",
    "OTTR": "Utilities",
    "OUST": "Industrials",
    "OVBC": "Finance",
    "OVID": "Health Care",
    "OVLY": "Finance",
    "OWLS": "Technology",
    "OXBR": "Finance",
    "OXLC": "Finance",
    "OXSQ": "Finance",
    "OYSE": "Finance",
    "OZK": "Finance",
    "PAAC": "Finance",
    "PACB": "Industrials",
    "PACH": "Unknown",
    "PAHC": "Health Care",
    "PAL": "Consumer Discretionary",
    "PALI": "Health Care",
    "PALO": "Finance",
    "PAMT": "Industrials",
    "PANL": "Consumer Discretionary",
    "PANW": "Technology",
    "PARA": "Industrials",
    "PARK": "Health Care",
    "PASG": "Health Care",
    "PASW": "Consumer Discretionary",
    "PATK": "Consumer Discretionary",
    "PAVM": "Health Care",
    "PAVS": "Technology",
    "PAX": "Finance",
    "PAYO": "Consumer Discretionary",
    "PAYP": "Consumer Discretionary",
    "PAYS": "Technology",
    "PAYX": "Industrials",
    "PBAM": "Finance",
    "PBFS": "Finance",
    "PBHC": "Finance",
    "PBK": "Utilities",
    "PBLS": "Health Care",
    "PBM": "Health Care",
    "PBYI": "Health Care",
    "PCAP": "Finance",
    "PCAR": "Industrials",
    "PCB": "Finance",
    "PCLA": "Consumer Discretionary",
    "PCRX": "Health Care",
    "PCSA": "Health Care",
    "PCT": "Industrials",
    "PCTY": "Technology",
    "PCVX": "Health Care",
    "PCYO": "Utilities",
    "PDC": "Technology",
    "PDD": "Consumer Discretionary",
    "PDEX": "Health Care",
    "PDFS": "Technology",
    "PDLB": "Finance",
    "PDSB": "Health Care",
    "PDYN": "Technology",
    "PEBK": "Finance",
    "PEBO": "Finance",
    "PECE": "Finance",
    "PECO": "Real Estate",
    "PEGA": "Technology",
    "PENG": "Technology",
    "PENN": "Consumer Discretionary",
    "PEP": "Consumer Staples",
    "PEPG": "Health Care",
    "PERI": "Technology",
    "PESI": "Industrials",
    "PETS": "Consumer Staples",
    "PETZ": "Finance",
    "PFAI": "Consumer Staples",
    "PFG": "Finance",
    "PFIS": "Finance",
    "PFSA": "Health Care",
    "PFX": "Finance",
    "PGAC": "Unknown",
    "PGC": "Finance",
    "PGEN": "Health Care",
    "PGNY": "Health Care",
    "PGY": "Finance",
    "PHAR": "Health Care",
    "PHAT": "Health Care",
    "PHIO": "Health Care",
    "PHOE": "Consumer Discretionary",
    "PHOS": "Industrials",
    "PHUN": "Technology",
    "PHVS": "Health Care",
    "PI": "Technology",
    "PICS": "Finance",
    "PIII": "Health Care",
    "PKBK": "Finance",
    "PKOH": "Industrials",
    "PLAB": "Technology",
    "PLAY": "Consumer Discretionary",
    "PLBC": "Finance",
    "PLBL": "Consumer Discretionary",
    "PLBY": "Consumer Discretionary",
    "PLCE": "Consumer Discretionary",
    "PLCI": "Finance",
    "PLMK": "Unknown",
    "PLMR": "Finance",
    "PLPC": "Industrials",
    "PLRX": "Health Care",
    "PLRZ": "Health Care",
    "PLSE": "Health Care",
    "PLSM": "Health Care",
    "PLTK": "Technology",
    "PLTR": "Technology",
    "PLUG": "Energy",
    "PLUR": "Health Care",
    "PLUS": "Technology",
    "PLUT": "Finance",
    "PLXS": "Technology",
    "PLYX": "Health Care",
    "PMA": "Consumer Discretionary",
    "PMAX": "Consumer Discretionary",
    "PMCB": "Health Care",
    "PMEC": "Consumer Discretionary",
    "PMN": "Health Care",
    "PMTR": "Finance",
    "PMTS": "Consumer Discretionary",
    "PMVP": "Health Care",
    "PN": "Technology",
    "PNBK": "Finance",
    "PNRG": "Energy",
    "PNTG": "Health Care",
    "POCI": "Health Care",
    "PODC": "Technology",
    "PODD": "Health Care",
    "POET": "Technology",
    "POLA": "Miscellaneous",
    "POLE": "Unknown",
    "POM": "Consumer Discretionary",
    "PONO": "Finance",
    "PONY": "Technology",
    "POOL": "Consumer Discretionary",
    "POWI": "Technology",
    "POWL": "Energy",
    "POWW": "Industrials",
    "PPBT": "Health Care",
    "PPC": "Consumer Staples",
    "PPCB": "Health Care",
    "PPHC": "Unknown",
    "PPIH": "Industrials",
    "PPLI": "Technology",
    "PPSI": "Miscellaneous",
    "PPTA": "Basic Materials",
    "PRAA": "Finance",
    "PRAX": "Health Care",
    "PRCH": "Technology",
    "PRCT": "Health Care",
    "PRDO": "Real Estate",
    "PRE": "Finance",
    "PRFX": "Health Care",
    "PRGS": "Technology",
    "PRHI": "Finance",
    "PRLD": "Health Care",
    "PRME": "Health Care",
    "PROF": "Health Care",
    "PROK": "Health Care",
    "PROP": "Energy",
    "PROV": "Finance",
    "PRPL": "Consumer Discretionary",
    "PRPO": "Industrials",
    "PRQR": "Health Care",
    "PRSO": "Technology",
    "PRTA": "Health Care",
    "PRTH": "Consumer Discretionary",
    "PRTS": "Consumer Discretionary",
    "PRVA": "Health Care",
    "PRZO": "Industrials",
    "PSEC": "Finance",
    "PSHG": "Consumer Discretionary",
    "PSIG": "Industrials",
    "PSIX": "Industrials",
    "PSKY": "Industrials",
    "PSMT": "Consumer Discretionary",
    "PSNL": "Health Care",
    "PSNY": "Industrials",
    "PSNYW": "Industrials",
    "PSQL": "Technology",
    "PTAC": "Finance",
    "PTC": "Technology",
    "PTCT": "Health Care",
    "PTEN": "Energy",
    "PTGX": "Health Care",
    "PTLE": "Energy",
    "PTLO": "Consumer Discretionary",
    "PTN": "Health Care",
    "PTON": "Consumer Discretionary",
    "PTOR": "Finance",
    "PTRN": "Consumer Discretionary",
    "PUBM": "Technology",
    "PULM": "Health Care",
    "PURR": "Finance",
    "PUSA": "Consumer Discretionary",
    "PVLA": "Health Care",
    "PWCM": "Finance",
    "PWP": "Finance",
    "PWRL": "Unknown",
    "PXLW": "Technology",
    "PXS": "Consumer Discretionary",
    "PYPD": "Health Care",
    "PYPL": "Industrials",
    "PYXS": "Health Care",
    "PZZA": "Consumer Discretionary",
    "QADR": "Finance",
    "QBTS": "Technology",
    "QCLS": "Health Care",
    "QCOM": "Technology",
    "QCRH": "Finance",
    "QDEL": "Health Care",
    "QETA": "Finance",
    "QFIN": "Finance",
    "QH": "Consumer Discretionary",
    "QLYS": "Technology",
    "QMCO": "Technology",
    "QMLS": "Technology",
    "QNBC": "Finance",
    "QNCX": "Health Care",
    "QNME": "Industrials",
    "QNRX": "Health Care",
    "QNST": "Consumer Discretionary",
    "QNT": "Technology",
    "QNTM": "Health Care",
    "QQQX": "Finance",
    "QRHC": "Utilities",
    "QRVO": "Technology",
    "QS": "Miscellaneous",
    "QSEA": "Finance",
    "QSI": "Industrials",
    "QTEX": "Health Care",
    "QTI": "Health Care",
    "QTRX": "Industrials",
    "QTTB": "Health Care",
    "QUBT": "Technology",
    "QUCY": "Health Care",
    "QUIK": "Technology",
    "QUMS": "Unknown",
    "QURE": "Health Care",
    "QVCG": "Consumer Discretionary",
    "QXL": "Technology",
    "RACC": "Finance",
    "RACD": "Unknown",
    "RADX": "Health Care",
    "RAIL": "Industrials",
    "RAIN": "Technology",
    "RAND": "Finance",
    "RANG": "Finance",
    "RANI": "Health Care",
    "RAPP": "Health Care",
    "RARE": "Health Care",
    "RAVE": "Consumer Discretionary",
    "RAYA": "Consumer Discretionary",
    "RBB": "Finance",
    "RBBN": "Technology",
    "RBCAA": "Finance",
    "RBKB": "Finance",
    "RBNE": "Consumer Discretionary",
    "RCAT": "Technology",
    "RCBC": "Finance",
    "RCEL": "Health Care",
    "RCKT": "Health Care",
    "RCKY": "Consumer Discretionary",
    "RCMT": "Consumer Discretionary",
    "RCON": "Energy",
    "RCT": "Technology",
    "RDAC": "Unknown",
    "RDAG": "Finance",
    "RDCM": "Technology",
    "RDGT": "Consumer Staples",
    "RDHL": "Health Care",
    "RDI": "Consumer Discretionary",
    "RDIB": "Consumer Discretionary",
    "RDNT": "Health Care",
    "RDNW": "Technology",
    "RDVT": "Technology",
    "RDWR": "Consumer Discretionary",
    "RDZN": "Finance",
    "REAL": "Consumer Discretionary",
    "REAX": "Finance",
    "REBN": "Consumer Discretionary",
    "RECT": "Consumer Discretionary",
    "REFI": "Real Estate",
    "REFR": "Miscellaneous",
    "REG": "Real Estate",
    "REGN": "Health Care",
    "REKR": "Telecommunications",
    "RELL": "Technology",
    "RELY": "Consumer Discretionary",
    "RENT": "Consumer Discretionary",
    "RENX": "Utilities",
    "REPL": "Health Care",
    "RETO": "Industrials",
    "REVB": "Health Care",
    "REYN": "Consumer Discretionary",
    "RFAI": "Unknown",
    "RFAM": "Unknown",
    "RFIL": "Technology",
    "RGC": "Health Care",
    "RGCO": "Utilities",
    "RGEN": "Health Care",
    "RGLD": "Industrials",
    "RGNX": "Health Care",
    "RGP": "Consumer Discretionary",
    "RGS": "Consumer Discretionary",
    "RGTI": "Technology",
    "RIBB": "Unknown",
    "RICK": "Consumer Discretionary",
    "RIGL": "Health Care",
    "RILY": "Finance",
    "RIME": "Technology",
    "RIOT": "Finance",
    "RITR": "Finance",
    "RIVN": "Industrials",
    "RJET": "Consumer Discretionary",
    "RKDA": "Energy",
    "RKLB": "Industrials",
    "RKTO": "Health Care",
    "RLAY": "Health Care",
    "RLMD": "Health Care",
    "RLYB": "Health Care",
    "RMBI": "Finance",
    "RMBS": "Technology",
    "RMCF": "Consumer Staples",
    "RMCO": "Miscellaneous",
    "RMIX": "Industrials",
    "RML": "Unknown",
    "RMNI": "Consumer Discretionary",
    "RMR": "Consumer Discretionary",
    "RMSG": "Technology",
    "RMTI": "Health Care",
    "RNA": "Health Care",
    "RNAC": "Health Care",
    "RNAQ": "Unknown",
    "RNAZ": "Health Care",
    "RNGT": "Finance",
    "RNTX": "Health Care",
    "RNW": "Utilities",
    "RNXT": "Health Care",
    "ROAD": "Industrials",
    "ROC": "Technology",
    "ROCK": "Industrials",
    "ROIV": "Health Care",
    "ROKU": "Telecommunications",
    "ROMA": "Consumer Discretionary",
    "ROOT": "Finance",
    "ROP": "Industrials",
    "ROST": "Consumer Discretionary",
    "RPAY": "Consumer Discretionary",
    "RPD": "Technology",
    "RPGL": "Technology",
    "RPID": "Industrials",
    "RPRX": "Health Care",
    "RR": "Industrials",
    "RRBI": "Finance",
    "RREV": "Finance",
    "RRGB": "Consumer Discretionary",
    "RRR": "Consumer Discretionary",
    "RSSS": "Technology",
    "RSVR": "Consumer Discretionary",
    "RTAC": "Finance",
    "RTB": "Consumer Discretionary",
    "RUBI": "Consumer Discretionary",
    "RUM": "Technology",
    "RUN": "Miscellaneous",
    "RUSHA": "Consumer Discretionary",
    "RUSHB": "Consumer Discretionary",
    "RVMD": "Health Care",
    "RVSB": "Finance",
    "RVSN": "Industrials",
    "RWAY": "Finance",
    "RXRX": "Health Care",
    "RXST": "Health Care",
    "RXT": "Technology",
    "RYAAY": "Consumer Discretionary",
    "RYET": "Technology",
    "RYM": "Consumer Staples",
    "RYOJ": "Consumer Discretionary",
    "RYTM": "Health Care",
    "RZLT": "Health Care",
    "RZLV": "Technology",
    "SAAQ": "Finance",
    "SABR": "Technology",
    "SABS": "Health Care",
    "SAFT": "Finance",
    "SAFX": "Industrials",
    "SAGT": "Technology",
    "SAIA": "Industrials",
    "SAIC": "Technology",
    "SAIH": "Technology",
    "SAIL": "Technology",
    "SAMG": "Finance",
    "SANA": "Health Care",
    "SANG": "Technology",
    "SANM": "Technology",
    "SATL": "Technology",
    "SBAC": "Real Estate",
    "SBC": "Health Care",
    "SBCF": "Finance",
    "SBET": "Technology",
    "SBFG": "Finance",
    "SBFM": "Health Care",
    "SBGI": "Industrials",
    "SBLK": "Consumer Discretionary",
    "SBRA": "Real Estate",
    "SBUX": "Consumer Discretionary",
    "SCAG": "Consumer Discretionary",
    "SCHL": "Consumer Discretionary",
    "SCII": "Unknown",
    "SCKT": "Technology",
    "SCLX": "Health Care",
    "SCNI": "Health Care",
    "SCNX": "Health Care",
    "SCOR": "Consumer Discretionary",
    "SCPQ": "Unknown",
    "SCSC": "Technology",
    "SCTX": "Health Care",
    "SCWO": "Consumer Discretionary",
    "SCYX": "Health Care",
    "SCZM": "Basic Materials",
    "SDA": "Consumer Discretionary",
    "SDGR": "Health Care",
    "SDHI": "Finance",
    "SDOT": "Consumer Discretionary",
    "SDST": "Industrials",
    "SEAT": "Consumer Discretionary",
    "SEDG": "Technology",
    "SEED": "Consumer Staples",
    "SEER": "Industrials",
    "SEGG": "Technology",
    "SEIC": "Finance",
    "SELF": "Real Estate",
    "SENEA": "Consumer Staples",
    "SENEB": "Consumer Staples",
    "SENS": "Health Care",
    "SEPN": "Health Care",
    "SERA": "Health Care",
    "SERV": "Industrials",
    "SEV": "Industrials",
    "SEVN": "Real Estate",
    "SEZL": "Finance",
    "SFBC": "Finance",
    "SFD": "Consumer Staples",
    "SFHG": "Consumer Discretionary",
    "SFIX": "Consumer Discretionary",
    "SFM": "Consumer Staples",
    "SFNC": "Finance",
    "SFST": "Finance",
    "SFWL": "Industrials",
    "SGA": "Consumer Discretionary",
    "SGC": "Consumer Discretionary",
    "SGHT": "Health Care",
    "SGLD": "Unknown",
    "SGLY": "Industrials",
    "SGML": "Basic Materials",
    "SGMT": "Health Care",
    "SGP": "Health Care",
    "SGRX": "Finance",
    "SGRY": "Health Care",
    "SHAZ": "Technology",
    "SHBI": "Finance",
    "SHC": "Health Care",
    "SHEN": "Telecommunications",
    "SHFS": "Finance",
    "SHIM": "Industrials",
    "SHIP": "Consumer Discretionary",
    "SHLS": "Technology",
    "SHMD": "Technology",
    "SHOE": "Consumer Discretionary",
    "SHOO": "Consumer Discretionary",
    "SHOP": "Technology",
    "SHOT": "Unknown",
    "SHPH": "Health Care",
    "SIBN": "Health Care",
    "SIDU": "Telecommunications",
    "SIEB": "Finance",
    "SIFY": "Technology",
    "SIGA": "Health Care",
    "SIGI": "Finance",
    "SILC": "Telecommunications",
    "SILO": "Health Care",
    "SIMA": "Miscellaneous",
    "SIMO": "Technology",
    "SINT": "Health Care",
    "SION": "Health Care",
    "SIRI": "Consumer Discretionary",
    "SITM": "Technology",
    "SJ": "Technology",
    "SKHY": "Technology",
    "SKIN": "Health Care",
    "SKK": "Industrials",
    "SKWD": "Finance",
    "SKYA": "Health Care",
    "SKYE": "Health Care",
    "SKYQ": "Industrials",
    "SKYW": "Consumer Discretionary",
    "SKYX": "Consumer Discretionary",
    "SLAB": "Technology",
    "SLBT": "Health Care",
    "SLDB": "Health Care",
    "SLDE": "Finance",
    "SLDP": "Miscellaneous",
    "SLE": "Technology",
    "SLGB": "Industrials",
    "SLGL": "Health Care",
    "SLM": "Finance",
    "SLMT": "Consumer Discretionary",
    "SLN": "Health Care",
    "SLNG": "Utilities",
    "SLNH": "Technology",
    "SLP": "Technology",
    "SLRC": "Finance",
    "SLS": "Health Care",
    "SLSN": "Consumer Discretionary",
    "SLXN": "Health Care",
    "SMBC": "Finance",
    "SMCI": "Technology",
    "SMID": "Industrials",
    "SMMT": "Health Care",
    "SMPL": "Consumer Staples",
    "SMSI": "Technology",
    "SMTC": "Technology",
    "SMTI": "Health Care",
    "SMTK": "Technology",
    "SMX": "Technology",
    "SMXT": "Consumer Discretionary",
    "SNAL": "Technology",
    "SND": "Industrials",
    "SNDK": "Technology",
    "SNDL": "Health Care",
    "SNDX": "Health Care",
    "SNES": "Industrials",
    "SNEX": "Finance",
    "SNFCA": "Finance",
    "SNGX": "Health Care",
    "SNOA": "Health Care",
    "SNPS": "Technology",
    "SNT": "Telecommunications",
    "SNTG": "Finance",
    "SNTI": "Health Care",
    "SNWV": "Health Care",
    "SNY": "Health Care",
    "SNYR": "Health Care",
    "SOBR": "Consumer Discretionary",
    "SOCA": "Unknown",
    "SOFI": "Finance",
    "SOGP": "Technology",
    "SOHU": "Technology",
    "SOLS": "Industrials",
    "SONM": "Utilities",
    "SONO": "Consumer Staples",
    "SOPH": "Technology",
    "SORA": "Industrials",
    "SORN": "Finance",
    "SOTK": "Technology",
    "SOUN": "Technology",
    "SOWG": "Consumer Staples",
    "SPAI": "Health Care",
    "SPCB": "Technology",
    "SPCX": "Technology",
    "SPEG": "Unknown",
    "SPFI": "Finance",
    "SPHL": "Consumer Discretionary",
    "SPKL": "Unknown",
    "SPOK": "Telecommunications",
    "SPPL": "Consumer Discretionary",
    "SPRB": "Health Care",
    "SPRC": "Health Care",
    "SPRO": "Health Care",
    "SPRY": "Health Care",
    "SPSC": "Technology",
    "SPT": "Technology",
    "SPTX": "Health Care",
    "SPWH": "Consumer Discretionary",
    "SPWR": "Technology",
    "SQFT": "Real Estate",
    "SRAD": "Technology",
    "SRBK": "Finance",
    "SRCE": "Finance",
    "SRPT": "Health Care",
    "SRRK": "Health Care",
    "SRTA": "Health Care",
    "SRTS": "Health Care",
    "SRZN": "Health Care",
    "SSAC": "Finance",
    "SSBI": "Finance",
    "SSEA": "Finance",
    "SSII": "Health Care",
    "SSM": "Technology",
    "SSNC": "Technology",
    "SSP": "Industrials",
    "SSRM": "Industrials",
    "SSTI": "Technology",
    "SSYS": "Technology",
    "STAA": "Health Care",
    "STAK": "Consumer Discretionary",
    "STBA": "Finance",
    "STEP": "Finance",
    "STEX": "Health Care",
    "STFS": "Consumer Discretionary",
    "STGW": "Consumer Discretionary",
    "STHO": "Real Estate",
    "STI": "Miscellaneous",
    "STIM": "Health Care",
    "STKE": "Unknown",
    "STKH": "Consumer Staples",
    "STKS": "Consumer Discretionary",
    "STLD": "Industrials",
    "STLN": "Health Care",
    "STNE": "Technology",
    "STOK": "Health Care",
    "STRA": "Real Estate",
    "STRL": "Industrials",
    "STRO": "Health Care",
    "STRR": "Consumer Discretionary",
    "STRT": "Consumer Discretionary",
    "STRZ": "Consumer Discretionary",
    "STTK": "Health Care",
    "STX": "Technology",
    "SUGP": "Consumer Discretionary",
    "SUIG": "Finance",
    "SUJA": "Consumer Staples",
    "SUMA": "Unknown",
    "SUNE": "Consumer Discretionary",
    "SUNS": "Real Estate",
    "SUPN": "Health Care",
    "SUPX": "Unknown",
    "SURG": "Consumer Discretionary",
    "SVAQ": "Finance",
    "SVC": "Real Estate",
    "SVCC": "Unknown",
    "SVCO": "Technology",
    "SVIV": "Finance",
    "SVRA": "Health Care",
    "SVRE": "Technology",
    "SVRN": "Consumer Discretionary",
    "SWAG": "Consumer Discretionary",
    "SWBI": "Industrials",
    "SWIM": "Industrials",
    "SWKS": "Technology",
    "SWMR": "Technology",
    "SWRD": "Finance",
    "SWVL": "Consumer Discretionary",
    "SXTC": "Health Care",
    "SXTP": "Health Care",
    "SY": "Technology",
    "SYBT": "Finance",
    "SYM": "Industrials",
    "SYNA": "Technology",
    "SYPR": "Industrials",
    "SYRE": "Health Care",
    "SZZL": "Finance",
    "TACH": "Finance",
    "TACO": "Finance",
    "TACT": "Technology",
    "TANH": "Industrials",
    "TAOP": "Technology",
    "TAOX": "Finance",
    "TARA": "Health Care",
    "TARS": "Health Care",
    "TASK": "Technology",
    "TATT": "Industrials",
    "TAVI": "Finance",
    "TAYD": "Industrials",
    "TBBK": "Finance",
    "TBCH": "Telecommunications",
    "TBLA": "Technology",
    "TBLD": "Finance",
    "TBPH": "Health Care",
    "TC": "Consumer Discretionary",
    "TCBI": "Finance",
    "TCBK": "Finance",
    "TCBS": "Finance",
    "TCGX": "Unknown",
    "TCMD": "Health Care",
    "TCOM": "Consumer Discretionary",
    "TCPC": "Finance",
    "TCRT": "Health Care",
    "TCRX": "Health Care",
    "TCX": "Technology",
    "TDAC": "Unknown",
    "TDIC": "Consumer Discretionary",
    "TDTH": "Consumer Discretionary",
    "TDUP": "Consumer Discretionary",
    "TDWD": "Finance",
    "TEAD": "Technology",
    "TEAM": "Technology",
    "TECH": "Health Care",
    "TECX": "Health Care",
    "TELA": "Health Care",
    "TELO": "Health Care",
    "TEM": "Technology",
    "TENB": "Technology",
    "TENX": "Health Care",
    "TER": "Industrials",
    "TFSL": "Finance",
    "TGHL": "Technology",
    "TGL": "Consumer Discretionary",
    "TGTX": "Health Care",
    "TH": "Consumer Discretionary",
    "THCH": "Consumer Discretionary",
    "THEO": "Finance",
    "THFF": "Finance",
    "THH": "Consumer Discretionary",
    "THRM": "Consumer Discretionary",
    "THRY": "Consumer Discretionary",
    "TIGO": "Telecommunications",
    "TIGR": "Finance",
    "TIL": "Health Care",
    "TILE": "Consumer Discretionary",
    "TIPT": "Finance",
    "TITN": "Consumer Discretionary",
    "TJGC": "Consumer Discretionary",
    "TKLF": "Consumer Discretionary",
    "TKNO": "Health Care",
    "TLF": "Consumer Discretionary",
    "TLIH": "Consumer Discretionary",
    "TLN": "Utilities",
    "TLNC": "Finance",
    "TLPH": "Health Care",
    "TLRY": "Health Care",
    "TLS": "Technology",
    "TLSA": "Health Care",
    "TLSI": "Health Care",
    "TLX": "Health Care",
    "TMC": "Basic Materials",
    "TMCI": "Health Care",
    "TMCR": "Basic Materials",
    "TMDX": "Health Care",
    "TMS": "Unknown",
    "TMTS": "Unknown",
    "TMUS": "Telecommunications",
    "TNDM": "Health Care",
    "TNGX": "Health Care",
    "TNMG": "Consumer Discretionary",
    "TNON": "Health Care",
    "TNXP": "Health Care",
    "TNYA": "Health Care",
    "TOMZ": "Industrials",
    "TONX": "Finance",
    "TOP": "Finance",
    "TORO": "Consumer Discretionary",
    "TOUR": "Consumer Discretionary",
    "TOWN": "Finance",
    "TOYO": "Consumer Discretionary",
    "TPCS": "Industrials",
    "TPG": "Finance",
    "TPST": "Health Care",
    "TRAW": "Health Care",
    "TRAX": "Health Care",
    "TRBG": "Utilities",
    "TRDA": "Health Care",
    "TREE": "Finance",
    "TREO": "Basic Materials",
    "TRGS": "Finance",
    "TRI": "Consumer Discretionary",
    "TRIB": "Health Care",
    "TRIP": "Technology",
    "TRMB": "Industrials",
    "TRMD": "Consumer Discretionary",
    "TRMK": "Finance",
    "TRNR": "Technology",
    "TRNS": "Industrials",
    "TRON": "Finance",
    "TROO": "Finance",
    "TROW": "Finance",
    "TRS": "Industrials",
    "TRSG": "Industrials",
    "TRST": "Finance",
    "TRUG": "Consumer Discretionary",
    "TRUP": "Health Care",
    "TRVG": "Technology",
    "TRVI": "Health Care",
    "TSAT": "Industrials",
    "TSBK": "Finance",
    "TSCO": "Consumer Discretionary",
    "TSEM": "Technology",
    "TSHA": "Health Care",
    "TSLA": "Industrials",
    "TSSI": "Consumer Discretionary",
    "TTAN": "Technology",
    "TTD": "Technology",
    "TTEC": "Consumer Discretionary",
    "TTEK": "Consumer Discretionary",
    "TTGT": "Telecommunications",
    "TTMI": "Technology",
    "TTRX": "Health Care",
    "TTWO": "Technology",
    "TULP": "Consumer Staples",
    "TURB": "Miscellaneous",
    "TUSK": "Energy",
    "TVA": "Unknown",
    "TVAI": "Unknown",
    "TVGN": "Health Care",
    "TVIV": "Unknown",
    "TVRD": "Health Care",
    "TVTX": "Health Care",
    "TW": "Finance",
    "TWAV": "Technology",
    "TWFG": "Finance",
    "TWG": "Consumer Staples",
    "TWIN": "Industrials",
    "TWLV": "Finance",
    "TWST": "Health Care",
    "TXG": "Industrials",
    "TXMD": "Health Care",
    "TXN": "Technology",
    "TXRH": "Consumer Discretionary",
    "TYGO": "Technology",
    "TYRA": "Health Care",
    "TZOO": "Consumer Discretionary",
    "UAL": "Consumer Discretionary",
    "UBCP": "Finance",
    "UBSI": "Finance",
    "UCAR": "Miscellaneous",
    "UCL": "Consumer Discretionary",
    "UCTT": "Technology",
    "UEIC": "Consumer Staples",
    "UFCS": "Finance",
    "UFG": "Energy",
    "UFPI": "Basic Materials",
    "UFPT": "Health Care",
    "UG": "Consumer Discretionary",
    "UK": "Consumer Discretionary",
    "ULBI": "Miscellaneous",
    "ULCC": "Consumer Discretionary",
    "ULH": "Industrials",
    "ULTA": "Consumer Discretionary",
    "UMBF": "Finance",
    "UNB": "Finance",
    "UNCY": "Health Care",
    "UNIT": "Real Estate",
    "UNTY": "Finance",
    "UONE": "Consumer Discretionary",
    "UONEK": "Consumer Discretionary",
    "UPB": "Health Care",
    "UPBD": "Consumer Discretionary",
    "UPC": "Health Care",
    "UPLD": "Technology",
    "UPST": "Finance",
    "UPWK": "Technology",
    "UPXI": "Finance",
    "URBN": "Consumer Discretionary",
    "URGN": "Health Care",
    "UROY": "Finance",
    "USAR": "Basic Materials",
    "USAU": "Basic Materials",
    "USCB": "Finance",
    "USDE": "Finance",
    "USEA": "Consumer Discretionary",
    "USGO": "Basic Materials",
    "USIO": "Finance",
    "USLM": "Industrials",
    "UTHR": "Health Care",
    "UTMD": "Health Care",
    "UTSI": "Telecommunications",
    "UVSP": "Finance",
    "UXIN": "Consumer Discretionary",
    "UYSC": "Finance",
    "UZX": "Consumer Discretionary",
    "VABK": "Finance",
    "VAI": "Consumer Discretionary",
    "VALN": "Health Care",
    "VALU": "Finance",
    "VANI": "Health Care",
    "VBIO": "Health Care",
    "VBNK": "Finance",
    "VC": "Consumer Discretionary",
    "VCEL": "Health Care",
    "VCIG": "Consumer Discretionary",
    "VCRE": "Health Care",
    "VCTR": "Finance",
    "VCYT": "Health Care",
    "VECO": "Technology",
    "VEEA": "Technology",
    "VEEE": "Industrials",
    "VELO": "Technology",
    "VEON": "Telecommunications",
    "VERA": "Health Care",
    "VERI": "Technology",
    "VERU": "Health Care",
    "VERX": "Technology",
    "VFF": "Consumer Staples",
    "VFS": "Industrials",
    "VGAS": "Industrials",
    "VHC": "Miscellaneous",
    "VHCP": "Unknown",
    "VHUB": "Technology",
    "VIAV": "Technology",
    "VICR": "Technology",
    "VINP": "Finance",
    "VIOT": "Consumer Discretionary",
    "VIP": "Finance",
    "VIR": "Health Care",
    "VIRC": "Consumer Discretionary",
    "VISN": "Technology",
    "VITL": "Consumer Staples",
    "VIVK": "Utilities",
    "VIVO": "Utilities",
    "VIVS": "Health Care",
    "VKTX": "Health Care",
    "VLGEA": "Consumer Staples",
    "VLOS": "Unknown",
    "VLY": "Finance",
    "VMAR": "Industrials",
    "VMD": "Health Care",
    "VMET": "Industrials",
    "VNCE": "Consumer Discretionary",
    "VNDA": "Health Care",
    "VNET": "Technology",
    "VNME": "Finance",
    "VNOM": "Energy",
    "VOD": "Telecommunications",
    "VOGX": "Health Care",
    "VOR": "Health Care",
    "VOXR": "Basic Materials",
    "VRA": "Consumer Discretionary",
    "VRAX": "Health Care",
    "VRCA": "Health Care",
    "VRDN": "Health Care",
    "VREX": "Technology",
    "VRM": "Consumer Discretionary",
    "VRME": "Technology",
    "VRNS": "Technology",
    "VRRM": "Consumer Discretionary",
    "VRSK": "Technology",
    "VRSN": "Technology",
    "VRTX": "Health Care",
    "VRXA": "Health Care",
    "VS": "Technology",
    "VSA": "Real Estate",
    "VSAT": "Consumer Discretionary",
    "VSEC": "Consumer Discretionary",
    "VSME": "Consumer Discretionary",
    "VSNT": "Industrials",
    "VSTM": "Health Care",
    "VTGN": "Health Care",
    "VTIX": "Technology",
    "VTRS": "Health Care",
    "VTSI": "Consumer Discretionary",
    "VTVT": "Health Care",
    "VUZI": "Technology",
    "VVOS": "Health Care",
    "VWAV": "Technology",
    "VYGR": "Health Care",
    "WABC": "Finance",
    "WAFD": "Finance",
    "WAFDP": "Finance",
    "WAFU": "Real Estate",
    "WALD": "Consumer Discretionary",
    "WASH": "Finance",
    "WATR": "Consumer Staples",
    "WATT": "Technology",
    "WAVE": "Utilities",
    "WAY": "Technology",
    "WB": "Technology",
    "WBD": "Telecommunications",
    "WBTN": "Consumer Discretionary",
    "WBUY": "Consumer Discretionary",
    "WCT": "Technology",
    "WDAY": "Technology",
    "WDC": "Technology",
    "WDFC": "Industrials",
    "WEN": "Consumer Discretionary",
    "WENN": "Unknown",
    "WERN": "Industrials",
    "WEST": "Consumer Staples",
    "WETH": "Technology",
    "WETO": "Industrials",
    "WEYS": "Consumer Staples",
    "WFCF": "Technology",
    "WFF": "Consumer Discretionary",
    "WFRD": "Consumer Discretionary",
    "WGS": "Health Care",
    "WHF": "Finance",
    "WHLR": "Real Estate",
    "WHWK": "Health Care",
    "WIMI": "Technology",
    "WINA": "Consumer Discretionary",
    "WING": "Consumer Discretionary",
    "WIX": "Technology",
    "WKEY": "Technology",
    "WKHS": "Industrials",
    "WKSP": "Consumer Discretionary",
    "WLCO": "Finance",
    "WLDN": "Consumer Discretionary",
    "WLDS": "Telecommunications",
    "WLFC": "Consumer Discretionary",
    "WLII": "Finance",
    "WLTH": "Finance",
    "WMG": "Consumer Discretionary",
    "WMT": "Consumer Discretionary",
    "WNEB": "Finance",
    "WNW": "Consumer Discretionary",
    "WOK": "Health Care",
    "WOOF": "Consumer Discretionary",
    "WPRT": "Industrials",
    "WRAP": "Industrials",
    "WRD": "Technology",
    "WRLD": "Finance",
    "WSBC": "Finance",
    "WSBF": "Finance",
    "WSBK": "Finance",
    "WSC": "Industrials",
    "WSE": "Industrials",
    "WSFS": "Finance",
    "WSHP": "Consumer Discretionary",
    "WSTN": "Technology",
    "WTBA": "Finance",
    "WTF": "Finance",
    "WTFC": "Finance",
    "WTG": "Finance",
    "WTW": "Finance",
    "WULF": "Finance",
    "WVE": "Health Care",
    "WVVI": "Consumer Staples",
    "WW": "Consumer Discretionary",
    "WWD": "Energy",
    "WXM": "Consumer Discretionary",
    "WYFI": "Finance",
    "WYHG": "Consumer Staples",
    "WYNN": "Consumer Discretionary",
    "XAIR": "Health Care",
    "XBIO": "Health Care",
    "XBIT": "Health Care",
    "XBP": "Technology",
    "XCBE": "Unknown",
    "XCH": "Miscellaneous",
    "XCUR": "Health Care",
    "XE": "Industrials",
    "XEL": "Utilities",
    "XELB": "Miscellaneous",
    "XELLL": "Utilities",
    "XENE": "Health Care",
    "XERS": "Health Care",
    "XFOR": "Health Care",
    "XGN": "Health Care",
    "XHG": "Finance",
    "XHLD": "Consumer Discretionary",
    "XLAB": "Technology",
    "XLO": "Health Care",
    "XMAX": "Consumer Discretionary",
    "XMTR": "Consumer Discretionary",
    "XNCR": "Health Care",
    "XNDU": "Technology",
    "XNET": "Technology",
    "XOS": "Consumer Discretionary",
    "XP": "Finance",
    "XPEL": "Industrials",
    "XPON": "Miscellaneous",
    "XRAY": "Health Care",
    "XRPN": "Finance",
    "XRTX": "Health Care",
    "XRX": "Technology",
    "XSLL": "Finance",
    "XTER": "Unknown",
    "XTIA": "Technology",
    "XTLB": "Health Care",
    "XWEL": "Consumer Discretionary",
    "XXII": "Health Care",
    "YAAS": "Technology",
    "YARW": "Health Care",
    "YB": "Finance",
    "YDDL": "Consumer Discretionary",
    "YDES": "Health Care",
    "YDKG": "Consumer Discretionary",
    "YFOR": "Consumer Discretionary",
    "YHC": "Consumer Staples",
    "YHGJ": "Industrials",
    "YHNA": "Unknown",
    "YI": "Consumer Staples",
    "YIBO": "Technology",
    "YICC": "Finance",
    "YJ": "Consumer Discretionary",
    "YMAT": "Consumer Discretionary",
    "YMT": "Technology",
    "YORW": "Utilities",
    "YOUL": "Real Estate",
    "YQ": "Real Estate",
    "YSWY": "Consumer Staples",
    "YSXT": "Consumer Discretionary",
    "YTRA": "Consumer Discretionary",
    "YXT": "Technology",
    "YYAI": "Technology",
    "Z": "Consumer Discretionary",
    "ZBAO": "Finance",
    "ZBIO": "Health Care",
    "ZBRA": "Industrials",
    "ZCMD": "Real Estate",
    "ZD": "Telecommunications",
    "ZDAI": "Consumer Discretionary",
    "ZENA": "Technology",
    "ZEO": "Miscellaneous",
    "ZG": "Consumer Discretionary",
    "ZION": "Finance",
    "ZJK": "Industrials",
    "ZJYL": "Health Care",
    "ZKIN": "Industrials",
    "ZKP": "Finance",
    "ZLAB": "Health Care",
    "ZM": "Technology",
    "ZNB": "Real Estate",
    "ZNTL": "Health Care",
    "ZOOZ": "Technology",
    "ZS": "Technology",
    "ZSQR": "Finance",
    "ZSTK": "Health Care",
    "ZTG": "Consumer Discretionary",
    "ZUMZ": "Consumer Discretionary",
    "ZURA": "Health Care",
    "ZVRA": "Health Care",
    "ZYBT": "Health Care",
    "ZYME": "Health Care",
}

NASDAQ_SYMBOLS: list[str] = list(NASDAQ_SECTORS.keys())
