"""NYSE-listed constituent tickers (common stock, ADRs, REITs, etc. -
warrants/rights/units/preferred/notes filtered out; dual-class symbols
hyphenated for Yahoo Finance, e.g. BRK/B -> BRK-B) mapped to a sector
label, used only by the NYSE ranking tab - independent of the
hand-curated dashboard watchlist in symbols.py.

Sourced from https://github.com/rreichel3/US-Stock-Symbols
(nyse/nyse_full_tickers.json, off Nasdaq's own listings), snapshot taken
2026-09-21. Sector labels come from Nasdaq's own (non-GICS) classification
and are blank for some newer/thinly-covered listings, shown here as
"Unknown". The actual list drifts over time (new listings, delistings)
and this snapshot will too; stale tickers are harmlessly skipped by the scan.
"""

NYSE_SECTORS: dict[str, str] = {
    "A": "Industrials",
    "AA": "Industrials",
    "AAC": "Industrials",
    "AADX": "Industrials",
    "AAMI": "Finance",
    "AAP": "Consumer Discretionary",
    "AAT": "Real Estate",
    "AAUC": "Unknown",
    "ABBV": "Health Care",
    "ABCB": "Finance",
    "ABEV": "Consumer Staples",
    "ABG": "Consumer Discretionary",
    "ABM": "Consumer Discretionary",
    "ABR": "Real Estate",
    "ABT": "Health Care",
    "ABX": "Finance",
    "ACA": "Industrials",
    "ACCO": "Consumer Discretionary",
    "ACEL": "Consumer Discretionary",
    "ACH": "Health Care",
    "ACHR": "Industrials",
    "ACI": "Consumer Staples",
    "ACM": "Consumer Discretionary",
    "ACN": "Consumer Discretionary",
    "ACP": "Finance",
    "ACR": "Real Estate",
    "ACRE": "Real Estate",
    "ACV": "Finance",
    "ACVA": "Consumer Discretionary",
    "AD": "Telecommunications",
    "ADC": "Real Estate",
    "ADCT": "Health Care",
    "ADIG": "Industrials",
    "ADM": "Consumer Staples",
    "ADNT": "Consumer Discretionary",
    "ADT": "Consumer Discretionary",
    "ADX": "Finance",
    "AEE": "Utilities",
    "AEG": "Finance",
    "AEM": "Basic Materials",
    "AEO": "Consumer Discretionary",
    "AER": "Consumer Discretionary",
    "AERO": "Consumer Discretionary",
    "AES": "Industrials",
    "AESI": "Industrials",
    "AEXA": "Unknown",
    "AFB": "Finance",
    "AFG": "Finance",
    "AFL": "Finance",
    "AG": "Basic Materials",
    "AGBK": "Finance",
    "AGCO": "Industrials",
    "AGD": "Finance",
    "AGI": "Basic Materials",
    "AGL": "Health Care",
    "AGM": "Finance",
    "AGO": "Finance",
    "AGRO": "Consumer Staples",
    "AGX": "Consumer Discretionary",
    "AHR": "Real Estate",
    "AHRT": "Finance",
    "AHT": "Real Estate",
    "AI": "Technology",
    "AIG": "Finance",
    "AII": "Finance",
    "AIIA": "Finance",
    "AIN": "Consumer Discretionary",
    "AIO": "Finance",
    "AIR": "Industrials",
    "AIT": "Consumer Discretionary",
    "AIV": "Real Estate",
    "AIZ": "Finance",
    "AJG": "Finance",
    "AKA": "Consumer Discretionary",
    "AKO-A": "Unknown",
    "AKO-B": "Unknown",
    "AKR": "Real Estate",
    "ALB": "Industrials",
    "ALC": "Health Care",
    "ALG": "Industrials",
    "ALH": "Industrials",
    "ALIT": "Consumer Discretionary",
    "ALK": "Consumer Discretionary",
    "ALL": "Finance",
    "ALLE": "Consumer Discretionary",
    "ALLY": "Finance",
    "ALSN": "Consumer Discretionary",
    "ALTG": "Industrials",
    "ALUB": "Unknown",
    "ALV": "Consumer Discretionary",
    "ALX": "Real Estate",
    "AM": "Utilities",
    "AMBP": "Industrials",
    "AMBQ": "Technology",
    "AMC": "Consumer Discretionary",
    "AMCR": "Consumer Discretionary",
    "AME": "Industrials",
    "AMG": "Finance",
    "AMH": "Real Estate",
    "AMN": "Consumer Discretionary",
    "AMP": "Finance",
    "AMPX": "Miscellaneous",
    "AMPY": "Energy",
    "AMR": "Energy",
    "AMRC": "Consumer Discretionary",
    "AMRZ": "Industrials",
    "AMT": "Real Estate",
    "AMTB": "Finance",
    "AMTD": "Finance",
    "AMTM": "Consumer Discretionary",
    "AMWL": "Consumer Discretionary",
    "AN": "Consumer Discretionary",
    "ANDG": "Consumer Discretionary",
    "ANET": "Telecommunications",
    "ANF": "Consumer Discretionary",
    "ANGX": "Consumer Discretionary",
    "ANRO": "Health Care",
    "ANVS": "Health Care",
    "AOD": "Finance",
    "AOMR": "Finance",
    "AON": "Finance",
    "AORT": "Health Care",
    "AOS": "Consumer Discretionary",
    "AP": "Industrials",
    "APAM": "Finance",
    "APD": "Basic Materials",
    "APG": "Consumer Discretionary",
    "APH": "Technology",
    "APLE": "Real Estate",
    "APO": "Finance",
    "APTV": "Consumer Discretionary",
    "AQN": "Utilities",
    "AR": "Energy",
    "ARCO": "Consumer Discretionary",
    "ARDC": "Finance",
    "ARDT": "Health Care",
    "ARE": "Real Estate",
    "ARES": "Finance",
    "ARI": "Real Estate",
    "ARIS": "Unknown",
    "ARL": "Finance",
    "ARLO": "Consumer Discretionary",
    "ARMK": "Consumer Discretionary",
    "AROC": "Utilities",
    "ARR": "Real Estate",
    "ARW": "Technology",
    "ARX": "Finance",
    "AS": "Consumer Discretionary",
    "ASA": "Industrials",
    "ASAN": "Technology",
    "ASB": "Finance",
    "ASBH": "Unknown",
    "ASC": "Consumer Discretionary",
    "ASG": "Finance",
    "ASGI": "Finance",
    "ASH": "Consumer Discretionary",
    "ASIC": "Finance",
    "ASIX": "Industrials",
    "ASPN": "Consumer Discretionary",
    "ASR": "Consumer Discretionary",
    "ASX": "Technology",
    "ATEN": "Telecommunications",
    "ATHM": "Technology",
    "ATI": "Industrials",
    "ATKR": "Miscellaneous",
    "ATMU": "Consumer Discretionary",
    "ATO": "Utilities",
    "ATR": "Industrials",
    "ATS": "Industrials",
    "AU": "Basic Materials",
    "AUB": "Finance",
    "AUNA": "Health Care",
    "AVA": "Utilities",
    "AVBC": "Finance",
    "AVD": "Industrials",
    "AVEX": "Industrials",
    "AVK": "Finance",
    "AVNT": "Industrials",
    "AVTR": "Industrials",
    "AVY": "Consumer Discretionary",
    "AWF": "Finance",
    "AWI": "Industrials",
    "AWK": "Utilities",
    "AWP": "Finance",
    "AWR": "Utilities",
    "AX": "Finance",
    "AXP": "Finance",
    "AXR": "Real Estate",
    "AXS": "Finance",
    "AXTA": "Consumer Discretionary",
    "AYI": "Consumer Discretionary",
    "AZN": "Health Care",
    "AZO": "Consumer Discretionary",
    "AZUL": "Consumer Discretionary",
    "AZZ": "Industrials",
    "B": "Basic Materials",
    "BA": "Industrials",
    "BABA": "Consumer Discretionary",
    "BAC": "Finance",
    "BAH": "Consumer Discretionary",
    "BAK": "Industrials",
    "BALL": "Industrials",
    "BALY": "Consumer Discretionary",
    "BAM": "Real Estate",
    "BANC": "Finance",
    "BAP": "Finance",
    "BARK": "Consumer Discretionary",
    "BAX": "Health Care",
    "BB": "Technology",
    "BBAI": "Technology",
    "BBAR": "Finance",
    "BBD": "Finance",
    "BBDC": "Finance",
    "BBDO": "Finance",
    "BBN": "Finance",
    "BBT": "Finance",
    "BBUC": "Consumer Discretionary",
    "BBVA": "Finance",
    "BBW": "Consumer Discretionary",
    "BBWI": "Consumer Discretionary",
    "BBY": "Consumer Discretionary",
    "BC": "Industrials",
    "BCAT": "Finance",
    "BCC": "Consumer Discretionary",
    "BCE": "Telecommunications",
    "BCH": "Finance",
    "BCO": "Industrials",
    "BCS": "Finance",
    "BCSF": "Finance",
    "BCSS": "Unknown",
    "BCX": "Finance",
    "BDC": "Industrials",
    "BDJ": "Finance",
    "BDN": "Real Estate",
    "BDX": "Health Care",
    "BE": "Energy",
    "BEBE": "Consumer Discretionary",
    "BEKE": "Finance",
    "BEN": "Finance",
    "BEPC": "Utilities",
    "BETA": "Industrials",
    "BF-A": "Unknown",
    "BF-B": "Unknown",
    "BFAM": "Consumer Discretionary",
    "BFH": "Consumer Discretionary",
    "BFLY": "Health Care",
    "BFS": "Real Estate",
    "BG": "Consumer Staples",
    "BGB": "Finance",
    "BGH": "Finance",
    "BGR": "Finance",
    "BGS": "Consumer Staples",
    "BGSF": "Consumer Discretionary",
    "BGSI": "Unknown",
    "BGT": "Finance",
    "BGX": "Finance",
    "BGY": "Finance",
    "BH": "Consumer Discretionary",
    "BHC": "Health Care",
    "BHE": "Technology",
    "BHK": "Finance",
    "BHP": "Energy",
    "BHR": "Real Estate",
    "BHV": "Finance",
    "BHVN": "Health Care",
    "BIII": "Finance",
    "BILL": "Technology",
    "BIO": "Industrials",
    "BIO-B": "Unknown",
    "BIPC": "Consumer Discretionary",
    "BIRK": "Consumer Discretionary",
    "BIT": "Finance",
    "BJ": "Consumer Discretionary",
    "BKD": "Health Care",
    "BKE": "Consumer Discretionary",
    "BKH": "Utilities",
    "BKKT": "Finance",
    "BKSY": "Technology",
    "BKT": "Finance",
    "BKU": "Finance",
    "BKV": "Energy",
    "BLCO": "Health Care",
    "BLDR": "Consumer Discretionary",
    "BLK": "Finance",
    "BLND": "Technology",
    "BLSH": "Finance",
    "BLW": "Consumer Discretionary",
    "BLX": "Finance",
    "BMA": "Finance",
    "BME": "Finance",
    "BMEZ": "Finance",
    "BMI": "Industrials",
    "BMN": "Finance",
    "BMNR": "Finance",
    "BMO": "Finance",
    "BMY": "Health Care",
    "BN": "Real Estate",
    "BNED": "Consumer Discretionary",
    "BNL": "Real Estate",
    "BNS": "Finance",
    "BNT": "Finance",
    "BNY": "Finance",
    "BOBS": "Consumer Discretionary",
    "BOC": "Finance",
    "BOE": "Finance",
    "BOH": "Finance",
    "BOOT": "Consumer Discretionary",
    "BORR": "Energy",
    "BOW": "Finance",
    "BOX": "Technology",
    "BP": "Energy",
    "BPRE": "Unknown",
    "BR": "Consumer Discretionary",
    "BRBR": "Consumer Staples",
    "BRC": "Consumer Discretionary",
    "BRCC": "Consumer Staples",
    "BRK-A": "Unknown",
    "BRK-B": "Unknown",
    "BRO": "Finance",
    "BROS": "Consumer Discretionary",
    "BRSL": "Consumer Discretionary",
    "BRSP": "Real Estate",
    "BRT": "Real Estate",
    "BRW": "Finance",
    "BRX": "Real Estate",
    "BSAC": "Finance",
    "BSL": "Finance",
    "BST": "Finance",
    "BSTZ": "Finance",
    "BSX": "Health Care",
    "BTE": "Energy",
    "BTGO": "Finance",
    "BTI": "Health Care",
    "BTO": "Finance",
    "BTT": "Finance",
    "BTU": "Energy",
    "BTX": "Unknown",
    "BTZ": "Finance",
    "BUD": "Consumer Staples",
    "BUI": "Finance",
    "BUR": "Finance",
    "BURL": "Consumer Discretionary",
    "BV": "Consumer Staples",
    "BVN": "Basic Materials",
    "BW": "Industrials",
    "BWA": "Consumer Discretionary",
    "BWG": "Finance",
    "BWIV": "Finance",
    "BWLP": "Consumer Discretionary",
    "BWMX": "Consumer Discretionary",
    "BWXT": "Industrials",
    "BX": "Finance",
    "BXC": "Consumer Discretionary",
    "BXDC": "Finance",
    "BXMT": "Real Estate",
    "BXP": "Real Estate",
    "BXSL": "Finance",
    "BY": "Finance",
    "BYD": "Consumer Discretionary",
    "BZH": "Consumer Discretionary",
    "C": "Finance",
    "CAAP": "Consumer Discretionary",
    "CABO": "Telecommunications",
    "CACI": "Technology",
    "CAF": "Finance",
    "CAG": "Consumer Staples",
    "CAH": "Health Care",
    "CAL": "Consumer Discretionary",
    "CALX": "Consumer Discretionary",
    "CALY": "Consumer Discretionary",
    "CANG": "Finance",
    "CARR": "Industrials",
    "CARS": "Technology",
    "CAT": "Industrials",
    "CATO": "Consumer Discretionary",
    "CAVA": "Consumer Discretionary",
    "CB": "Finance",
    "CBAN": "Finance",
    "CBL": "Real Estate",
    "CBNA": "Finance",
    "CBRE": "Finance",
    "CBT": "Industrials",
    "CBU": "Finance",
    "CBZ": "Consumer Discretionary",
    "CC": "Industrials",
    "CCI": "Real Estate",
    "CCIF": "Finance",
    "CCJ": "Basic Materials",
    "CCK": "Industrials",
    "CCL": "Consumer Discretionary",
    "CCM": "Health Care",
    "CCO": "Consumer Discretionary",
    "CCS": "Consumer Discretionary",
    "CCU": "Consumer Staples",
    "CCZ": "Telecommunications",
    "CDE": "Basic Materials",
    "CDLR": "Consumer Discretionary",
    "CDP": "Real Estate",
    "CDRE": "Health Care",
    "CE": "Industrials",
    "CEE": "Finance",
    "CEPU": "Utilities",
    "CF": "Industrials",
    "CFG": "Finance",
    "CFND": "Unknown",
    "CFR": "Finance",
    "CGAU": "Basic Materials",
    "CHCT": "Real Estate",
    "CHD": "Consumer Discretionary",
    "CHE": "Health Care",
    "CHGG": "Real Estate",
    "CHH": "Consumer Discretionary",
    "CHMI": "Real Estate",
    "CHPT": "Miscellaneous",
    "CHT": "Telecommunications",
    "CHWY": "Consumer Discretionary",
    "CI": "Health Care",
    "CIA": "Finance",
    "CIEN": "Utilities",
    "CIG": "Utilities",
    "CII": "Finance",
    "CIM": "Real Estate",
    "CINT": "Technology",
    "CION": "Finance",
    "CL": "Consumer Discretionary",
    "CLB": "Energy",
    "CLBR": "Unknown",
    "CLDT": "Real Estate",
    "CLF": "Basic Materials",
    "CLH": "Industrials",
    "CLPR": "Real Estate",
    "CLS": "Technology",
    "CLVT": "Technology",
    "CLW": "Basic Materials",
    "CLX": "Consumer Discretionary",
    "CM": "Finance",
    "CMBT": "Consumer Discretionary",
    "CMC": "Industrials",
    "CMCM": "Technology",
    "CMDB": "Consumer Discretionary",
    "CMG": "Consumer Discretionary",
    "CMI": "Industrials",
    "CMP": "Industrials",
    "CMRE": "Consumer Discretionary",
    "CMS": "Utilities",
    "CMTG": "Finance",
    "CNA": "Finance",
    "CNC": "Health Care",
    "CNF": "Finance",
    "CNH": "Industrials",
    "CNI": "Industrials",
    "CNK": "Consumer Discretionary",
    "CNM": "Consumer Discretionary",
    "CNMD": "Health Care",
    "CNNE": "Consumer Discretionary",
    "CNO": "Finance",
    "CNP": "Utilities",
    "CNQ": "Energy",
    "CNR": "Energy",
    "CNS": "Finance",
    "CNX": "Energy",
    "CODI": "Consumer Discretionary",
    "COF": "Finance",
    "COHR": "Technology",
    "COLD": "Real Estate",
    "COMP": "Finance",
    "CON": "Health Care",
    "COOK": "Consumer Discretionary",
    "COP": "Energy",
    "COPL": "Unknown",
    "COR": "Health Care",
    "COSO": "Finance",
    "COTY": "Consumer Discretionary",
    "COUR": "Technology",
    "CP": "Industrials",
    "CPA": "Consumer Discretionary",
    "CPAC": "Industrials",
    "CPAY": "Consumer Discretionary",
    "CPF": "Finance",
    "CPK": "Utilities",
    "CPNG": "Consumer Discretionary",
    "CPRI": "Consumer Discretionary",
    "CPS": "Consumer Discretionary",
    "CPT": "Real Estate",
    "CR": "Industrials",
    "CRBG": "Finance",
    "CRC": "Energy",
    "CRCL": "Finance",
    "CRD-A": "Unknown",
    "CRD-B": "Unknown",
    "CRGY": "Energy",
    "CRH": "Industrials",
    "CRI": "Consumer Discretionary",
    "CRK": "Energy",
    "CRL": "Health Care",
    "CRM": "Technology",
    "CRS": "Industrials",
    "CRT": "Energy",
    "CSAN": "Consumer Discretionary",
    "CSL": "Industrials",
    "CSQR": "Technology",
    "CSR": "Real Estate",
    "CSTM": "Industrials",
    "CSV": "Consumer Discretionary",
    "CSW": "Industrials",
    "CTEV": "Consumer Discretionary",
    "CTO": "Real Estate",
    "CTOS": "Consumer Discretionary",
    "CTRE": "Real Estate",
    "CTRI": "Utilities",
    "CTS": "Technology",
    "CTVA": "Consumer Staples",
    "CUBE": "Real Estate",
    "CUBI": "Finance",
    "CURB": "Finance",
    "CURV": "Consumer Discretionary",
    "CUZ": "Real Estate",
    "CVE": "Energy",
    "CVEO": "Consumer Discretionary",
    "CVI": "Energy",
    "CVLG": "Industrials",
    "CVNA": "Consumer Discretionary",
    "CVS": "Consumer Staples",
    "CVSA": "Real Estate",
    "CVX": "Energy",
    "CW": "Technology",
    "CWEN": "Utilities",
    "CWH": "Consumer Discretionary",
    "CWK": "Finance",
    "CWT": "Utilities",
    "CX": "Industrials",
    "CXM": "Technology",
    "CXT": "Industrials",
    "CXW": "Real Estate",
    "CYD": "Industrials",
    "CYH": "Health Care",
    "D": "Utilities",
    "DAC": "Consumer Discretionary",
    "DAL": "Consumer Discretionary",
    "DAN": "Consumer Discretionary",
    "DAO": "Real Estate",
    "DAR": "Consumer Staples",
    "DAVA": "Technology",
    "DB": "Finance",
    "DBD": "Miscellaneous",
    "DBI": "Consumer Discretionary",
    "DBL": "Unknown",
    "DBRG": "Real Estate",
    "DCH": "Consumer Discretionary",
    "DCI": "Industrials",
    "DCO": "Industrials",
    "DCOM": "Finance",
    "DD": "Industrials",
    "DDD": "Technology",
    "DDL": "Consumer Discretionary",
    "DDS": "Consumer Discretionary",
    "DDT": "Consumer Discretionary",
    "DE": "Industrials",
    "DEA": "Real Estate",
    "DEC": "Unknown",
    "DECK": "Consumer Discretionary",
    "DEI": "Real Estate",
    "DELL": "Technology",
    "DEO": "Consumer Staples",
    "DFH": "Consumer Discretionary",
    "DFIN": "Consumer Discretionary",
    "DG": "Consumer Discretionary",
    "DGAC": "Unknown",
    "DGX": "Health Care",
    "DHF": "Finance",
    "DHI": "Consumer Discretionary",
    "DHR": "Industrials",
    "DHT": "Consumer Discretionary",
    "DHX": "Consumer Discretionary",
    "DIN": "Consumer Discretionary",
    "DINO": "Energy",
    "DIS": "Consumer Discretionary",
    "DK": "Energy",
    "DKS": "Consumer Discretionary",
    "DLB": "Miscellaneous",
    "DLR": "Real Estate",
    "DLX": "Consumer Discretionary",
    "DLY": "Finance",
    "DMA": "Finance",
    "DMB": "Finance",
    "DMC": "Consumer Staples",
    "DMO": "Finance",
    "DNA": "Health Care",
    "DNOW": "Consumer Discretionary",
    "DNP": "Finance",
    "DOC": "Real Estate",
    "DOCN": "Technology",
    "DOCS": "Technology",
    "DOLE": "Consumer Staples",
    "DOUG": "Finance",
    "DOV": "Industrials",
    "DOW": "Industrials",
    "DPC": "Telecommunications",
    "DPG": "Finance",
    "DQ": "Technology",
    "DRD": "Basic Materials",
    "DRI": "Consumer Discretionary",
    "DSL": "Finance",
    "DSM": "Finance",
    "DSU": "Finance",
    "DSX": "Consumer Discretionary",
    "DT": "Technology",
    "DTE": "Utilities",
    "DTF": "Finance",
    "DTM": "Utilities",
    "DUK": "Utilities",
    "DV": "Technology",
    "DVA": "Health Care",
    "DVN": "Energy",
    "DX": "Real Estate",
    "DXC": "Technology",
    "DXYZ": "Unknown",
    "DY": "Industrials",
    "E": "Energy",
    "EAF": "Energy",
    "EARN": "Real Estate",
    "EAT": "Consumer Discretionary",
    "EBF": "Consumer Discretionary",
    "EBS": "Health Care",
    "EC": "Energy",
    "ECAT": "Finance",
    "ECC": "Finance",
    "ECG": "Consumer Discretionary",
    "ECL": "Consumer Discretionary",
    "ECO": "Consumer Discretionary",
    "ECVT": "Industrials",
    "ED": "Utilities",
    "EDD": "Finance",
    "EDF": "Finance",
    "EDN": "Utilities",
    "EDU": "Real Estate",
    "EE": "Utilities",
    "EEA": "Finance",
    "EFC": "Finance",
    "EFOR": "Consumer Discretionary",
    "EFR": "Finance",
    "EFT": "Finance",
    "EFX": "Finance",
    "EFXT": "Industrials",
    "EG": "Finance",
    "EGO": "Basic Materials",
    "EGP": "Real Estate",
    "EGY": "Energy",
    "EHC": "Health Care",
    "EHI": "Finance",
    "EIC": "Finance",
    "EIG": "Finance",
    "EIX": "Utilities",
    "EL": "Consumer Discretionary",
    "ELAN": "Health Care",
    "ELC": "Utilities",
    "ELF": "Consumer Discretionary",
    "ELME": "Real Estate",
    "ELPC": "Utilities",
    "ELS": "Real Estate",
    "ELV": "Health Care",
    "EMA": "Utilities",
    "EMBJ": "Industrials",
    "EMD": "Finance",
    "EME": "Industrials",
    "EMF": "Finance",
    "EMN": "Industrials",
    "EMO": "Finance",
    "EMR": "Technology",
    "ENB": "Energy",
    "ENHA": "Consumer Discretionary",
    "ENIC": "Utilities",
    "ENOV": "Health Care",
    "ENR": "Miscellaneous",
    "ENS": "Miscellaneous",
    "ENVA": "Finance",
    "EOD": "Finance",
    "EOG": "Energy",
    "EOI": "Finance",
    "EOS": "Finance",
    "EOT": "Finance",
    "EPAC": "Technology",
    "EPAM": "Technology",
    "EPC": "Consumer Discretionary",
    "EPD": "Utilities",
    "EPR": "Real Estate",
    "EPRT": "Real Estate",
    "EQBK": "Finance",
    "EQH": "Finance",
    "EQNR": "Energy",
    "EQS": "Finance",
    "EQT": "Energy",
    "ERO": "Basic Materials",
    "EROC": "Energy",
    "EROK": "Energy",
    "ES": "Utilities",
    "ESAB": "Industrials",
    "ESE": "Telecommunications",
    "ESI": "Industrials",
    "ESNT": "Finance",
    "ESRT": "Real Estate",
    "ESS": "Real Estate",
    "ESTC": "Technology",
    "ETB": "Finance",
    "ETD": "Consumer Discretionary",
    "ETG": "Finance",
    "ETJ": "Finance",
    "ETN": "Technology",
    "ETO": "Finance",
    "ETR": "Utilities",
    "ETSS": "Finance",
    "ETSY": "Consumer Discretionary",
    "ETV": "Finance",
    "ETW": "Finance",
    "ETX": "Finance",
    "ETY": "Finance",
    "EVAC": "Industrials",
    "EVC": "Industrials",
    "EVEX": "Industrials",
    "EVF": "Finance",
    "EVG": "Finance",
    "EVH": "Consumer Discretionary",
    "EVMN": "Health Care",
    "EVN": "Finance",
    "EVR": "Finance",
    "EVT": "Finance",
    "EVTC": "Technology",
    "EVTL": "Industrials",
    "EW": "Health Care",
    "EXG": "Finance",
    "EXK": "Basic Materials",
    "EXP": "Industrials",
    "EXPD": "Industrials",
    "EXR": "Real Estate",
    "F": "Industrials",
    "FAF": "Finance",
    "FBIN": "Basic Materials",
    "FBK": "Finance",
    "FBP": "Finance",
    "FBRT": "Real Estate",
    "FC": "Consumer Discretionary",
    "FCBM": "Finance",
    "FCF": "Finance",
    "FCN": "Consumer Discretionary",
    "FCPT": "Real Estate",
    "FCRS": "Finance",
    "FCX": "Basic Materials",
    "FDS": "Technology",
    "FDX": "Consumer Discretionary",
    "FDXF": "Consumer Discretionary",
    "FE": "Utilities",
    "FEDU": "Real Estate",
    "FENG": "Industrials",
    "FERG": "Miscellaneous",
    "FET": "Consumer Discretionary",
    "FF": "Industrials",
    "FFA": "Finance",
    "FG": "Finance",
    "FHI": "Finance",
    "FHN": "Finance",
    "FICO": "Consumer Discretionary",
    "FIG": "Technology",
    "FIGS": "Consumer Discretionary",
    "FINS": "Finance",
    "FINV": "Finance",
    "FIRY": "Technology",
    "FIS": "Consumer Discretionary",
    "FITB": "Finance",
    "FIX": "Industrials",
    "FLC": "Finance",
    "FLG": "Finance",
    "FLNG": "Consumer Discretionary",
    "FLO": "Consumer Staples",
    "FLOC": "Consumer Discretionary",
    "FLR": "Industrials",
    "FLS": "Industrials",
    "FLUT": "Technology",
    "FMC": "Industrials",
    "FMN": "Finance",
    "FMS": "Health Care",
    "FMX": "Consumer Staples",
    "FMY": "Finance",
    "FN": "Utilities",
    "FNB": "Finance",
    "FND": "Consumer Discretionary",
    "FNF": "Finance",
    "FNV": "Basic Materials",
    "FOA": "Finance",
    "FOF": "Finance",
    "FOIL": "Industrials",
    "FOR": "Finance",
    "FOUR": "Consumer Discretionary",
    "FPH": "Finance",
    "FPI": "Real Estate",
    "FPS": "Energy",
    "FR": "Real Estate",
    "FRA": "Finance",
    "FRO": "Consumer Discretionary",
    "FRT": "Real Estate",
    "FSCO": "Finance",
    "FSK": "Finance",
    "FSM": "Basic Materials",
    "FSS": "Industrials",
    "FSSL": "Finance",
    "FT": "Finance",
    "FTHY": "Finance",
    "FTI": "Consumer Discretionary",
    "FTK": "Industrials",
    "FTRA": "Unknown",
    "FTS": "Utilities",
    "FTV": "Industrials",
    "FTW": "Energy",
    "FUBO": "Consumer Discretionary",
    "FUL": "Industrials",
    "FUN": "Consumer Discretionary",
    "FVR": "Real Estate",
    "FVRR": "Consumer Discretionary",
    "G": "Consumer Discretionary",
    "GAB": "Finance",
    "GAM": "Finance",
    "GAP": "Consumer Discretionary",
    "GATX": "Consumer Discretionary",
    "GBAB": "Finance",
    "GBCI": "Finance",
    "GBTG": "Consumer Discretionary",
    "GBX": "Industrials",
    "GCO": "Consumer Discretionary",
    "GCTS": "Technology",
    "GCV": "Finance",
    "GD": "Industrials",
    "GDDY": "Technology",
    "GDL": "Finance",
    "GDO": "Finance",
    "GDOT": "Finance",
    "GDV": "Finance",
    "GE": "Technology",
    "GEF": "Unknown",
    "GENI": "Consumer Discretionary",
    "GEO": "Consumer Discretionary",
    "GETY": "Consumer Discretionary",
    "GEV": "Technology",
    "GF": "Finance",
    "GFF": "Industrials",
    "GFI": "Basic Materials",
    "GFL": "Utilities",
    "GFR": "Energy",
    "GGB": "Industrials",
    "GGG": "Industrials",
    "GGT": "Finance",
    "GGZ": "Finance",
    "GHC": "Real Estate",
    "GHG": "Consumer Discretionary",
    "GHM": "Industrials",
    "GHY": "Finance",
    "GIB": "Consumer Discretionary",
    "GIC": "Industrials",
    "GIL": "Consumer Discretionary",
    "GIS": "Consumer Staples",
    "GJO": "Finance",
    "GJP": "Finance",
    "GJR": "Finance",
    "GJS": "Finance",
    "GJT": "Finance",
    "GKOS": "Health Care",
    "GL": "Finance",
    "GLAS": "Health Care",
    "GLED": "Finance",
    "GLOB": "Technology",
    "GLW": "Industrials",
    "GM": "Industrials",
    "GME": "Consumer Discretionary",
    "GMED": "Health Care",
    "GMRS": "Consumer Discretionary",
    "GNE": "Utilities",
    "GNK": "Consumer Discretionary",
    "GNL": "Real Estate",
    "GNRC": "Consumer Discretionary",
    "GNT": "Finance",
    "GNW": "Finance",
    "GOF": "Finance",
    "GOLD": "Industrials",
    "GOLF": "Consumer Discretionary",
    "GOOS": "Consumer Discretionary",
    "GOTU": "Real Estate",
    "GPC": "Consumer Discretionary",
    "GPGI": "Finance",
    "GPI": "Consumer Discretionary",
    "GPK": "Consumer Discretionary",
    "GPMT": "Real Estate",
    "GPN": "Consumer Discretionary",
    "GPOR": "Energy",
    "GPRK": "Energy",
    "GRBK": "Consumer Discretionary",
    "GRC": "Industrials",
    "GRDN": "Consumer Staples",
    "GRMN": "Industrials",
    "GRND": "Technology",
    "GRNT": "Energy",
    "GROV": "Consumer Discretionary",
    "GRX": "Finance",
    "GS": "Finance",
    "GSBD": "Finance",
    "GSK": "Health Care",
    "GSL": "Consumer Discretionary",
    "GTES": "Industrials",
    "GTN": "Industrials",
    "GTY": "Finance",
    "GUG": "Finance",
    "GUT": "Finance",
    "GVA": "Industrials",
    "GWH": "Miscellaneous",
    "GWRE": "Technology",
    "GWW": "Industrials",
    "GXO": "Consumer Discretionary",
    "H": "Consumer Discretionary",
    "HAE": "Health Care",
    "HAFN": "Consumer Discretionary",
    "HAL": "Energy",
    "HASI": "Finance",
    "HAWK": "Technology",
    "HAYW": "Industrials",
    "HBB": "Consumer Discretionary",
    "HBM": "Basic Materials",
    "HCA": "Health Care",
    "HCC": "Energy",
    "HCI": "Finance",
    "HD": "Consumer Discretionary",
    "HDB": "Finance",
    "HE": "Utilities",
    "HEI": "Industrials",
    "HEI-A": "Unknown",
    "HEQ": "Finance",
    "HESM": "Energy",
    "HFRO": "Finance",
    "HG": "Finance",
    "HGLB": "Finance",
    "HGTY": "Finance",
    "HGV": "Consumer Discretionary",
    "HHH": "Real Estate",
    "HIG": "Finance",
    "HII": "Industrials",
    "HIMS": "Health Care",
    "HIO": "Finance",
    "HIPO": "Finance",
    "HIW": "Real Estate",
    "HIX": "Finance",
    "HKD": "Finance",
    "HL": "Industrials",
    "HLF": "Health Care",
    "HLI": "Finance",
    "HLIO": "Industrials",
    "HLLY": "Consumer Discretionary",
    "HLN": "Consumer Discretionary",
    "HLT": "Consumer Discretionary",
    "HMC": "Industrials",
    "HMN": "Finance",
    "HMY": "Basic Materials",
    "HNGE": "Technology",
    "HNI": "Consumer Discretionary",
    "HOG": "Consumer Discretionary",
    "HOMB": "Finance",
    "HOS": "Energy",
    "HOV": "Consumer Discretionary",
    "HP": "Energy",
    "HPE": "Technology",
    "HPF": "Finance",
    "HPP": "Finance",
    "HPQ": "Technology",
    "HQH": "Finance",
    "HQL": "Finance",
    "HR": "Real Estate",
    "HRB": "Consumer Discretionary",
    "HRI": "Industrials",
    "HRL": "Consumer Staples",
    "HRTG": "Finance",
    "HSBC": "Finance",
    "HSHP": "Consumer Discretionary",
    "HSY": "Consumer Staples",
    "HTB": "Finance",
    "HTD": "Finance",
    "HTGC": "Finance",
    "HTH": "Finance",
    "HTT": "Finance",
    "HUBB": "Technology",
    "HUBS": "Technology",
    "HUM": "Health Care",
    "HUN": "Industrials",
    "HUYA": "Technology",
    "HVT": "Consumer Discretionary",
    "HVT-A": "Unknown",
    "HWM": "Industrials",
    "HXL": "Industrials",
    "HY": "Industrials",
    "HYI": "Finance",
    "HYT": "Finance",
    "HZO": "Consumer Discretionary",
    "IAE": "Finance",
    "IAG": "Basic Materials",
    "IBM": "Technology",
    "IBN": "Finance",
    "IBP": "Consumer Discretionary",
    "IBTA": "Consumer Discretionary",
    "ICE": "Finance",
    "ICL": "Industrials",
    "IDA": "Utilities",
    "IDE": "Finance",
    "IDT": "Telecommunications",
    "IEX": "Industrials",
    "IFF": "Industrials",
    "IFN": "Finance",
    "IFS": "Finance",
    "IGA": "Finance",
    "IGD": "Finance",
    "IGI": "Finance",
    "IGR": "Finance",
    "IH": "Real Estate",
    "IHD": "Finance",
    "IHG": "Consumer Discretionary",
    "IHS": "Telecommunications",
    "IIF": "Finance",
    "IIIN": "Industrials",
    "IIM": "Finance",
    "IIPR": "Finance",
    "IMAX": "Consumer Discretionary",
    "INFQ": "Technology",
    "INFY": "Technology",
    "ING": "Finance",
    "INGM": "Technology",
    "INGR": "Consumer Staples",
    "INN": "Real Estate",
    "INR": "Energy",
    "INSP": "Health Care",
    "INSW": "Consumer Discretionary",
    "INVH": "Finance",
    "INVX": "Consumer Discretionary",
    "IONQ": "Technology",
    "IOT": "Technology",
    "IP": "Basic Materials",
    "IPI": "Industrials",
    "IQI": "Finance",
    "IQV": "Health Care",
    "IR": "Industrials",
    "IRAB": "Unknown",
    "IRM": "Real Estate",
    "IRS": "Real Estate",
    "IRT": "Real Estate",
    "ISD": "Finance",
    "IT": "Consumer Discretionary",
    "ITGR": "Health Care",
    "ITT": "Industrials",
    "ITW": "Industrials",
    "IVR": "Real Estate",
    "IVT": "Real Estate",
    "IVZ": "Finance",
    "IX": "Finance",
    "J": "Industrials",
    "JACS": "Unknown",
    "JAN": "Real Estate",
    "JBGS": "Real Estate",
    "JBI": "Industrials",
    "JBL": "Technology",
    "JBS": "Consumer Staples",
    "JBTM": "Industrials",
    "JCE": "Finance",
    "JCI": "Industrials",
    "JEF": "Finance",
    "JELD": "Basic Materials",
    "JENA": "Finance",
    "JFR": "Finance",
    "JGH": "Finance",
    "JHI": "Finance",
    "JHS": "Finance",
    "JHX": "Industrials",
    "JILL": "Consumer Discretionary",
    "JKS": "Technology",
    "JLL": "Finance",
    "JLS": "Finance",
    "JMIA": "Consumer Discretionary",
    "JMKE": "Consumer Discretionary",
    "JMM": "Finance",
    "JNJ": "Health Care",
    "JOBY": "Industrials",
    "JOE": "Real Estate",
    "JOF": "Finance",
    "JPM": "Finance",
    "JQC": "Finance",
    "JRI": "Finance",
    "JRS": "Finance",
    "JXN": "Finance",
    "KAI": "Industrials",
    "KB": "Finance",
    "KBDC": "Unknown",
    "KBH": "Consumer Discretionary",
    "KBR": "Industrials",
    "KD": "Technology",
    "KEN": "Utilities",
    "KEP": "Utilities",
    "KEX": "Consumer Discretionary",
    "KEY": "Finance",
    "KEYS": "Industrials",
    "KF": "Finance",
    "KFRC": "Consumer Discretionary",
    "KFY": "Consumer Discretionary",
    "KGC": "Basic Materials",
    "KGS": "Utilities",
    "KHC": "Consumer Staples",
    "KIM": "Real Estate",
    "KIO": "Finance",
    "KKR": "Finance",
    "KLAR": "Finance",
    "KLC": "Consumer Discretionary",
    "KMI": "Utilities",
    "KMPR": "Finance",
    "KMT": "Industrials",
    "KMX": "Consumer Discretionary",
    "KN": "Consumer Staples",
    "KNF": "Industrials",
    "KNSL": "Finance",
    "KNTK": "Utilities",
    "KNX": "Industrials",
    "KO": "Consumer Staples",
    "KODK": "Consumer Discretionary",
    "KOP": "Basic Materials",
    "KOS": "Energy",
    "KPET": "Unknown",
    "KR": "Consumer Staples",
    "KRC": "Real Estate",
    "KREF": "Real Estate",
    "KRG": "Real Estate",
    "KRMN": "Industrials",
    "KRO": "Basic Materials",
    "KRSP": "Unknown",
    "KSS": "Consumer Discretionary",
    "KT": "Telecommunications",
    "KTB": "Industrials",
    "KTF": "Finance",
    "KVUE": "Consumer Discretionary",
    "KVYO": "Technology",
    "KWR": "Industrials",
    "KWY": "Finance",
    "KYN": "Finance",
    "L": "Finance",
    "LAC": "Basic Materials",
    "LAD": "Consumer Discretionary",
    "LADR": "Real Estate",
    "LANV": "Consumer Discretionary",
    "LAR": "Basic Materials",
    "LAW": "Technology",
    "LAZ": "Finance",
    "LB": "Energy",
    "LBRT": "Energy",
    "LCII": "Consumer Discretionary",
    "LCLN": "Finance",
    "LDI": "Finance",
    "LDOS": "Technology",
    "LEA": "Consumer Discretionary",
    "LEN": "Consumer Discretionary",
    "LEO": "Finance",
    "LEU": "Industrials",
    "LEVI": "Consumer Discretionary",
    "LFT": "Real Estate",
    "LGI": "Unknown",
    "LH": "Health Care",
    "LHX": "Industrials",
    "LII": "Industrials",
    "LION": "Consumer Discretionary",
    "LITB": "Consumer Discretionary",
    "LLY": "Health Care",
    "LMND": "Finance",
    "LMT": "Industrials",
    "LNC": "Finance",
    "LND": "Consumer Staples",
    "LNG": "Utilities",
    "LNN": "Industrials",
    "LOAR": "Industrials",
    "LOB": "Finance",
    "LOCL": "Consumer Staples",
    "LOMA": "Industrials",
    "LOW": "Consumer Discretionary",
    "LPG": "Consumer Discretionary",
    "LPL": "Technology",
    "LPX": "Basic Materials",
    "LRN": "Real Estate",
    "LSPD": "Technology",
    "LTC": "Real Estate",
    "LTH": "Consumer Discretionary",
    "LTM": "Consumer Discretionary",
    "LU": "Finance",
    "LUCK": "Consumer Discretionary",
    "LUMN": "Telecommunications",
    "LUV": "Consumer Discretionary",
    "LUXE": "Consumer Discretionary",
    "LVS": "Consumer Discretionary",
    "LVWR": "Consumer Discretionary",
    "LW": "Consumer Staples",
    "LXP": "Real Estate",
    "LXU": "Basic Materials",
    "LYB": "Industrials",
    "LYG": "Finance",
    "LYNX": "Industrials",
    "LYV": "Consumer Discretionary",
    "LZB": "Consumer Discretionary",
    "LZM": "Basic Materials",
    "M": "Consumer Discretionary",
    "MA": "Consumer Discretionary",
    "MAA": "Real Estate",
    "MAC": "Real Estate",
    "MAGN": "Basic Materials",
    "MAIN": "Finance",
    "MAIR": "Industrials",
    "MAN": "Consumer Discretionary",
    "MANE": "Health Care",
    "MANU": "Consumer Discretionary",
    "MAS": "Industrials",
    "MATV": "Basic Materials",
    "MATX": "Consumer Discretionary",
    "MAX": "Consumer Discretionary",
    "MBC": "Consumer Discretionary",
    "MBGL": "Consumer Discretionary",
    "MBI": "Finance",
    "MC": "Finance",
    "MCB": "Finance",
    "MCD": "Consumer Discretionary",
    "MCI": "Finance",
    "MCK": "Health Care",
    "MCN": "Unknown",
    "MCO": "Finance",
    "MCS": "Consumer Discretionary",
    "MCY": "Finance",
    "MD": "Health Care",
    "MDA": "Consumer Discretionary",
    "MDT": "Health Care",
    "MDU": "Industrials",
    "MEC": "Industrials",
    "MED": "Consumer Staples",
    "MEGI": "Finance",
    "MEI": "Technology",
    "MET": "Finance",
    "MFA": "Real Estate",
    "MFC": "Finance",
    "MFG": "Finance",
    "MFM": "Finance",
    "MG": "Consumer Discretionary",
    "MGA": "Consumer Discretionary",
    "MGF": "Finance",
    "MGM": "Consumer Discretionary",
    "MGY": "Energy",
    "MH": "Consumer Discretionary",
    "MHD": "Finance",
    "MHF": "Finance",
    "MHK": "Consumer Discretionary",
    "MHO": "Consumer Discretionary",
    "MIAX": "Finance",
    "MICC": "Consumer Staples",
    "MIN": "Finance",
    "MIR": "Industrials",
    "MITT": "Real Estate",
    "MIY": "Finance",
    "MKC": "Consumer Staples",
    "MKL": "Finance",
    "MLI": "Industrials",
    "MLM": "Industrials",
    "MLP": "Finance",
    "MLR": "Consumer Discretionary",
    "MMD": "Finance",
    "MMI": "Finance",
    "MMM": "Health Care",
    "MMS": "Consumer Discretionary",
    "MMT": "Finance",
    "MMU": "Finance",
    "MNSO": "Consumer Discretionary",
    "MNTN": "Consumer Discretionary",
    "MO": "Health Care",
    "MOD": "Consumer Discretionary",
    "MOGU": "Consumer Discretionary",
    "MOH": "Health Care",
    "MOS": "Industrials",
    "MOV": "Consumer Discretionary",
    "MP": "Basic Materials",
    "MPA": "Finance",
    "MPC": "Energy",
    "MPT": "Real Estate",
    "MPV": "Finance",
    "MQY": "Finance",
    "MRK": "Health Care",
    "MRP": "Finance",
    "MRSH": "Finance",
    "MS": "Finance",
    "MSA": "Health Care",
    "MSB": "Industrials",
    "MSC": "Consumer Discretionary",
    "MSCI": "Consumer Discretionary",
    "MSD": "Finance",
    "MSDL": "Unknown",
    "MSGE": "Consumer Discretionary",
    "MSGS": "Consumer Discretionary",
    "MSI": "Technology",
    "MSIF": "Finance",
    "MSM": "Industrials",
    "MT": "Industrials",
    "MTAL": "Basic Materials",
    "MTB": "Finance",
    "MTD": "Industrials",
    "MTDR": "Energy",
    "MTG": "Finance",
    "MTH": "Consumer Discretionary",
    "MTN": "Consumer Discretionary",
    "MTNE": "Unknown",
    "MTR": "Energy",
    "MTRN": "Industrials",
    "MTUS": "Industrials",
    "MTW": "Industrials",
    "MTX": "Basic Materials",
    "MTZ": "Industrials",
    "MUA": "Finance",
    "MUC": "Finance",
    "MUFG": "Finance",
    "MUJ": "Finance",
    "MUR": "Energy",
    "MUSA": "Consumer Discretionary",
    "MUX": "Basic Materials",
    "MWA": "Industrials",
    "MX": "Technology",
    "MXE": "Finance",
    "MXF": "Finance",
    "MYE": "Industrials",
    "MYI": "Finance",
    "MYN": "Finance",
    "MZYX": "Unknown",
    "NABL": "Technology",
    "NAC": "Finance",
    "NAD": "Finance",
    "NAN": "Finance",
    "NAT": "Consumer Discretionary",
    "NATL": "Miscellaneous",
    "NAZ": "Finance",
    "NBB": "Finance",
    "NBHC": "Finance",
    "NBR": "Energy",
    "NBXG": "Finance",
    "NC": "Energy",
    "NCA": "Finance",
    "NCDL": "Unknown",
    "NCLH": "Consumer Discretionary",
    "NCV": "Finance",
    "NCZ": "Finance",
    "NDMO": "Finance",
    "NE": "Energy",
    "NEA": "Finance",
    "NEE": "Utilities",
    "NEM": "Basic Materials",
    "NET": "Technology",
    "NEU": "Industrials",
    "NEXA": "Basic Materials",
    "NFG": "Utilities",
    "NFJ": "Finance",
    "NGG": "Utilities",
    "NGS": "Energy",
    "NGVC": "Consumer Staples",
    "NGVT": "Industrials",
    "NHI": "Real Estate",
    "NI": "Utilities",
    "NIC": "Finance",
    "NIE": "Finance",
    "NIM": "Finance",
    "NIO": "Industrials",
    "NIQ": "Technology",
    "NJR": "Utilities",
    "NKE": "Consumer Discretionary",
    "NKX": "Finance",
    "NL": "Basic Materials",
    "NLOP": "Real Estate",
    "NLY": "Real Estate",
    "NMAI": "Finance",
    "NMAX": "Industrials",
    "NMCO": "Finance",
    "NMG": "Basic Materials",
    "NMI": "Finance",
    "NMR": "Finance",
    "NMS": "Finance",
    "NMT": "Finance",
    "NMZ": "Finance",
    "NNI": "Finance",
    "NNN": "Real Estate",
    "NNY": "Finance",
    "NOA": "Energy",
    "NOAH": "Finance",
    "NOC": "Industrials",
    "NOG": "Energy",
    "NOK": "Technology",
    "NOMD": "Consumer Staples",
    "NOV": "Consumer Discretionary",
    "NOW": "Technology",
    "NP": "Finance",
    "NPB": "Finance",
    "NPCT": "Finance",
    "NPK": "Industrials",
    "NPKI": "Industrials",
    "NPO": "Industrials",
    "NPV": "Finance",
    "NPWR": "Energy",
    "NRDY": "Real Estate",
    "NREF": "Real Estate",
    "NRG": "Utilities",
    "NRGV": "Miscellaneous",
    "NRK": "Finance",
    "NRP": "Energy",
    "NRT": "Energy",
    "NSC": "Industrials",
    "NSP": "Consumer Discretionary",
    "NTB": "Finance",
    "NTR": "Industrials",
    "NTST": "Real Estate",
    "NU": "Finance",
    "NUE": "Industrials",
    "NUS": "Health Care",
    "NUV": "Finance",
    "NUVB": "Health Care",
    "NUW": "Finance",
    "NVG": "Finance",
    "NVGS": "Consumer Discretionary",
    "NVO": "Health Care",
    "NVR": "Consumer Discretionary",
    "NVRI": "Miscellaneous",
    "NVS": "Health Care",
    "NVST": "Health Care",
    "NVT": "Industrials",
    "NWAX": "Finance",
    "NWG": "Finance",
    "NWN": "Utilities",
    "NX": "Industrials",
    "NXDR": "Technology",
    "NXDT": "Real Estate",
    "NXE": "Basic Materials",
    "NXG": "Unknown",
    "NXP": "Finance",
    "NXRT": "Real Estate",
    "NYC": "Real Estate",
    "NYT": "Consumer Discretionary",
    "NZF": "Finance",
    "O": "Real Estate",
    "OBDC": "Finance",
    "OBK": "Finance",
    "OC": "Industrials",
    "OCAC": "Finance",
    "ODC": "Consumer Discretionary",
    "OEC": "Industrials",
    "OFG": "Finance",
    "OFRM": "Consumer Staples",
    "OGC": "Unknown",
    "OGE": "Utilities",
    "OGG": "Basic Materials",
    "OGN": "Health Care",
    "OGS": "Utilities",
    "OHI": "Real Estate",
    "OI": "Consumer Discretionary",
    "OIA": "Finance",
    "OII": "Energy",
    "OIS": "Consumer Discretionary",
    "OKE": "Utilities",
    "OKLO": "Utilities",
    "OLN": "Industrials",
    "OLP": "Real Estate",
    "OMC": "Consumer Discretionary",
    "OMF": "Finance",
    "ONIT": "Finance",
    "ONL": "Real Estate",
    "ONON": "Consumer Discretionary",
    "ONT": "Consumer Discretionary",
    "ONTO": "Industrials",
    "OOMA": "Technology",
    "OPFI": "Finance",
    "OPLN": "Consumer Discretionary",
    "OPP": "Finance",
    "OPTU": "Telecommunications",
    "OPY": "Finance",
    "OR": "Basic Materials",
    "ORA": "Utilities",
    "ORC": "Real Estate",
    "ORCL": "Technology",
    "ORI": "Finance",
    "ORN": "Industrials",
    "OSCR": "Health Care",
    "OSG": "Finance",
    "OSK": "Industrials",
    "OTAI": "Unknown",
    "OTF": "Unknown",
    "OTIS": "Technology",
    "OUT": "Real Estate",
    "OVV": "Energy",
    "OWL": "Finance",
    "OWLT": "Industrials",
    "OXM": "Industrials",
    "OXY": "Energy",
    "P": "Technology",
    "PAAS": "Basic Materials",
    "PAC": "Consumer Discretionary",
    "PACK": "Consumer Discretionary",
    "PACS": "Health Care",
    "PAG": "Consumer Discretionary",
    "PAGS": "Technology",
    "PAI": "Finance",
    "PAII": "Unknown",
    "PAM": "Utilities",
    "PAR": "Miscellaneous",
    "PARR": "Energy",
    "PATH": "Technology",
    "PAXS": "Finance",
    "PAY": "Consumer Discretionary",
    "PAYC": "Technology",
    "PB": "Finance",
    "PBA": "Energy",
    "PBF": "Energy",
    "PBH": "Health Care",
    "PBI": "Miscellaneous",
    "PBR": "Energy",
    "PBT": "Energy",
    "PCF": "Finance",
    "PCG": "Utilities",
    "PCM": "Finance",
    "PCN": "Finance",
    "PCOR": "Technology",
    "PCQ": "Finance",
    "PD": "Technology",
    "PDCC": "Unknown",
    "PDI": "Finance",
    "PDM": "Real Estate",
    "PDO": "Finance",
    "PDS": "Energy",
    "PDT": "Finance",
    "PDX": "Finance",
    "PEB": "Real Estate",
    "PEG": "Utilities",
    "PEN": "Health Care",
    "PEO": "Finance",
    "PERF": "Technology",
    "PEW": "Consumer Discretionary",
    "PFE": "Health Care",
    "PFGC": "Consumer Discretionary",
    "PFL": "Finance",
    "PFLT": "Finance",
    "PFN": "Finance",
    "PFS": "Finance",
    "PFSI": "Finance",
    "PG": "Consumer Discretionary",
    "PGP": "Finance",
    "PGR": "Finance",
    "PGZ": "Finance",
    "PH": "Industrials",
    "PHG": "Health Care",
    "PHI": "Telecommunications",
    "PHIN": "Consumer Discretionary",
    "PHK": "Finance",
    "PHM": "Consumer Discretionary",
    "PHR": "Consumer Discretionary",
    "PII": "Consumer Discretionary",
    "PIM": "Finance",
    "PINE": "Real Estate",
    "PINS": "Technology",
    "PIPR": "Finance",
    "PJT": "Finance",
    "PK": "Consumer Discretionary",
    "PKE": "Industrials",
    "PKG": "Consumer Discretionary",
    "PKX": "Industrials",
    "PL": "Technology",
    "PLD": "Real Estate",
    "PLGO": "Finance",
    "PLNT": "Consumer Discretionary",
    "PLOW": "Industrials",
    "PLUN": "Unknown",
    "PM": "Health Care",
    "PML": "Finance",
    "PMM": "Finance",
    "PMO": "Finance",
    "PMT": "Real Estate",
    "PNC": "Finance",
    "PNFP": "Finance",
    "PNI": "Finance",
    "PNNT": "Finance",
    "PNR": "Industrials",
    "PNW": "Utilities",
    "POR": "Utilities",
    "POST": "Consumer Staples",
    "PPG": "Consumer Discretionary",
    "PPL": "Utilities",
    "PPT": "Finance",
    "PR": "Energy",
    "PRG": "Consumer Discretionary",
    "PRGO": "Health Care",
    "PRI": "Finance",
    "PRIM": "Industrials",
    "PRKS": "Consumer Discretionary",
    "PRLB": "Industrials",
    "PRM": "Industrials",
    "PRMB": "Consumer Staples",
    "PRSU": "Consumer Discretionary",
    "PRU": "Finance",
    "PS": "Finance",
    "PSA": "Real Estate",
    "PSBD": "Unknown",
    "PSFE": "Consumer Discretionary",
    "PSN": "Technology",
    "PSO": "Consumer Discretionary",
    "PSQH": "Consumer Discretionary",
    "PSTL": "Real Estate",
    "PSUS": "Unknown",
    "PSX": "Energy",
    "PTY": "Finance",
    "PUK": "Finance",
    "PUMP": "Energy",
    "PVH": "Industrials",
    "PWR": "Industrials",
    "PXED": "Real Estate",
    "PYT": "Finance",
    "Q": "Technology",
    "QGEN": "Health Care",
    "QLEP": "Unknown",
    "QRED": "Finance",
    "QSR": "Consumer Discretionary",
    "QTWO": "Technology",
    "QUAD": "Consumer Discretionary",
    "QXO": "Consumer Discretionary",
    "R": "Consumer Discretionary",
    "RA": "Finance",
    "RAC": "Unknown",
    "RACE": "Industrials",
    "RAL": "Industrials",
    "RAMP": "Technology",
    "RBA": "Consumer Discretionary",
    "RBC": "Industrials",
    "RBLX": "Technology",
    "RBRK": "Technology",
    "RC": "Real Estate",
    "RCI": "Telecommunications",
    "RCL": "Consumer Discretionary",
    "RCS": "Finance",
    "RCUS": "Health Care",
    "RDDT": "Technology",
    "RDN": "Finance",
    "RDW": "Industrials",
    "RDY": "Health Care",
    "REF": "Consumer Discretionary",
    "RELX": "Consumer Discretionary",
    "RERE": "Consumer Discretionary",
    "RES": "Energy",
    "REX": "Industrials",
    "REXR": "Real Estate",
    "REZI": "Industrials",
    "RF": "Finance",
    "RFI": "Finance",
    "RFL": "Health Care",
    "RFM": "Finance",
    "RFMZ": "Finance",
    "RGA": "Finance",
    "RGR": "Industrials",
    "RGT": "Finance",
    "RH": "Consumer Discretionary",
    "RHI": "Consumer Discretionary",
    "RHLD": "Finance",
    "RHP": "Real Estate",
    "RIG": "Energy",
    "RIO": "Basic Materials",
    "RITM": "Real Estate",
    "RIV": "Finance",
    "RJF": "Finance",
    "RKT": "Finance",
    "RL": "Industrials",
    "RLI": "Finance",
    "RLJ": "Real Estate",
    "RLTY": "Finance",
    "RM": "Finance",
    "RMD": "Health Care",
    "RMI": "Finance",
    "RMM": "Finance",
    "RMMZ": "Finance",
    "RMT": "Finance",
    "RNG": "Technology",
    "RNGR": "Energy",
    "RNR": "Finance",
    "RNST": "Finance",
    "ROG": "Industrials",
    "ROK": "Industrials",
    "ROL": "Consumer Discretionary",
    "RPC": "Finance",
    "RPM": "Consumer Discretionary",
    "RPT": "Real Estate",
    "RQI": "Finance",
    "RRC": "Energy",
    "RRX": "Industrials",
    "RS": "Industrials",
    "RSF": "Finance",
    "RSG": "Utilities",
    "RSI": "Consumer Discretionary",
    "RSKD": "Consumer Discretionary",
    "RTO": "Consumer Discretionary",
    "RTX": "Industrials",
    "RVI": "Unknown",
    "RVII": "Unknown",
    "RVLV": "Consumer Discretionary",
    "RVT": "Finance",
    "RVTY": "Industrials",
    "RWT": "Real Estate",
    "RXO": "Consumer Discretionary",
    "RY": "Finance",
    "RYAM": "Basic Materials",
    "RYAN": "Finance",
    "RYN": "Real Estate",
    "RYZ": "Industrials",
    "S": "Technology",
    "SA": "Basic Materials",
    "SABA": "Unknown",
    "SAC": "Finance",
    "SAFE": "Real Estate",
    "SAGU": "Finance",
    "SAH": "Consumer Discretionary",
    "SAM": "Consumer Staples",
    "SAMO": "Unknown",
    "SAN": "Finance",
    "SAP": "Technology",
    "SAR": "Finance",
    "SARO": "Industrials",
    "SB": "Consumer Discretionary",
    "SBH": "Consumer Discretionary",
    "SBI": "Finance",
    "SBR": "Energy",
    "SBS": "Utilities",
    "SBSI": "Finance",
    "SBSW": "Basic Materials",
    "SBXD": "Unknown",
    "SBXE": "Unknown",
    "SCCO": "Basic Materials",
    "SCD": "Finance",
    "SCHW": "Finance",
    "SCI": "Consumer Discretionary",
    "SCL": "Consumer Discretionary",
    "SCM": "Finance",
    "SD": "Energy",
    "SDHC": "Consumer Discretionary",
    "SDHY": "Finance",
    "SDRL": "Energy",
    "SE": "Consumer Discretionary",
    "SECZ": "Finance",
    "SEG": "Consumer Discretionary",
    "SEI": "Consumer Discretionary",
    "SES": "Miscellaneous",
    "SF": "Finance",
    "SFBS": "Finance",
    "SFL": "Consumer Discretionary",
    "SG": "Consumer Discretionary",
    "SGHC": "Consumer Discretionary",
    "SGI": "Consumer Discretionary",
    "SGU": "Consumer Discretionary",
    "SHAK": "Consumer Discretionary",
    "SHEL": "Energy",
    "SHG": "Finance",
    "SHO": "Consumer Discretionary",
    "SHW": "Consumer Discretionary",
    "SI": "Health Care",
    "SID": "Industrials",
    "SIG": "Consumer Discretionary",
    "SII": "Finance",
    "SIND": "Basic Materials",
    "SITC": "Real Estate",
    "SITE": "Consumer Discretionary",
    "SJM": "Consumer Staples",
    "SJT": "Energy",
    "SKE": "Basic Materials",
    "SKIL": "Technology",
    "SKM": "Telecommunications",
    "SKT": "Real Estate",
    "SKY": "Consumer Discretionary",
    "SKYH": "Finance",
    "SLB": "Energy",
    "SLF": "Finance",
    "SLG": "Real Estate",
    "SLGN": "Industrials",
    "SLQT": "Finance",
    "SLVM": "Basic Materials",
    "SM": "Energy",
    "SMA": "Real Estate",
    "SMBK": "Finance",
    "SMC": "Utilities",
    "SMFG": "Finance",
    "SMG": "Industrials",
    "SMHI": "Consumer Discretionary",
    "SMP": "Consumer Discretionary",
    "SMR": "Industrials",
    "SMRT": "Technology",
    "SMWB": "Technology",
    "SN": "Consumer Discretionary",
    "SNA": "Consumer Discretionary",
    "SNAP": "Technology",
    "SNDA": "Health Care",
    "SNDR": "Industrials",
    "SNN": "Health Care",
    "SNOW": "Technology",
    "SNX": "Technology",
    "SO": "Utilities",
    "SOBO": "Energy",
    "SOC": "Energy",
    "SOLV": "Health Care",
    "SON": "Consumer Discretionary",
    "SONY": "Consumer Staples",
    "SOR": "Finance",
    "SOS": "Finance",
    "SOUL": "Consumer Discretionary",
    "SPB": "Miscellaneous",
    "SPCE": "Consumer Discretionary",
    "SPE": "Finance",
    "SPG": "Real Estate",
    "SPGI": "Finance",
    "SPH": "Consumer Discretionary",
    "SPHR": "Consumer Discretionary",
    "SPIR": "Consumer Discretionary",
    "SPMC": "Unknown",
    "SPNT": "Finance",
    "SPOT": "Consumer Discretionary",
    "SPRU": "Utilities",
    "SPXC": "Industrials",
    "SPXX": "Finance",
    "SQM": "Industrials",
    "SQNS": "Technology",
    "SR": "Utilities",
    "SRE": "Utilities",
    "SRFM": "Consumer Discretionary",
    "SRG": "Finance",
    "SRI": "Consumer Discretionary",
    "SRL": "Industrials",
    "SRV": "Finance",
    "SSB": "Finance",
    "SSD": "Consumer Discretionary",
    "SSL": "Energy",
    "SSMR": "Basic Materials",
    "SST": "Technology",
    "SSTK": "Technology",
    "ST": "Industrials",
    "STAG": "Real Estate",
    "STC": "Finance",
    "STDN": "Basic Materials",
    "STE": "Health Care",
    "STEM": "Technology",
    "STEW": "Finance",
    "STG": "Real Estate",
    "STK": "Finance",
    "STLA": "Industrials",
    "STM": "Technology",
    "STN": "Consumer Discretionary",
    "STNG": "Consumer Discretionary",
    "STT": "Finance",
    "STUB": "Consumer Discretionary",
    "STVN": "Health Care",
    "STWD": "Real Estate",
    "STZ": "Consumer Staples",
    "SU": "Energy",
    "SUI": "Real Estate",
    "SUNB": "Consumer Discretionary",
    "SUPV": "Finance",
    "SUZ": "Basic Materials",
    "SVV": "Consumer Discretionary",
    "SW": "Consumer Discretionary",
    "SWK": "Consumer Discretionary",
    "SWX": "Utilities",
    "SWZ": "Finance",
    "SXC": "Industrials",
    "SXI": "Industrials",
    "SXT": "Industrials",
    "SYF": "Finance",
    "SYK": "Health Care",
    "SYY": "Consumer Discretionary",
    "T": "Telecommunications",
    "TAC": "Utilities",
    "TAK": "Health Care",
    "TAL": "Real Estate",
    "TALO": "Energy",
    "TAP": "Consumer Staples",
    "TBBB": "Consumer Staples",
    "TBI": "Consumer Discretionary",
    "TBN": "Energy",
    "TCBX": "Finance",
    "TCI": "Real Estate",
    "TD": "Finance",
    "TDAY": "Consumer Discretionary",
    "TDC": "Technology",
    "TDF": "Finance",
    "TDG": "Industrials",
    "TDOC": "Health Care",
    "TDS": "Telecommunications",
    "TDW": "Consumer Discretionary",
    "TDY": "Industrials",
    "TE": "Technology",
    "TECK": "Industrials",
    "TEI": "Finance",
    "TEL": "Technology",
    "TEN": "Consumer Discretionary",
    "TEO": "Telecommunications",
    "TEVA": "Health Care",
    "TEX": "Industrials",
    "TFC": "Finance",
    "TFII": "Industrials",
    "TFIN": "Finance",
    "TFPM": "Industrials",
    "TFX": "Health Care",
    "TG": "Industrials",
    "TGE": "Consumer Discretionary",
    "TGLS": "Consumer Discretionary",
    "TGS": "Utilities",
    "TGT": "Consumer Discretionary",
    "THC": "Health Care",
    "THG": "Finance",
    "THO": "Industrials",
    "THQ": "Finance",
    "THW": "Finance",
    "TIC": "Consumer Discretionary",
    "TIMB": "Telecommunications",
    "TISI": "Consumer Discretionary",
    "TJX": "Consumer Discretionary",
    "TK": "Consumer Discretionary",
    "TKC": "Telecommunications",
    "TKO": "Consumer Discretionary",
    "TKR": "Industrials",
    "TLK": "Telecommunications",
    "TLYS": "Consumer Discretionary",
    "TM": "Industrials",
    "TME": "Consumer Discretionary",
    "TMO": "Industrials",
    "TNC": "Industrials",
    "TNET": "Consumer Discretionary",
    "TNK": "Consumer Discretionary",
    "TNL": "Consumer Discretionary",
    "TOL": "Consumer Discretionary",
    "TOST": "Technology",
    "TPB": "Consumer Discretionary",
    "TPC": "Consumer Discretionary",
    "TPL": "Energy",
    "TPR": "Consumer Discretionary",
    "TPVG": "Consumer Discretionary",
    "TR": "Consumer Staples",
    "TRAD": "Finance",
    "TRAK": "Technology",
    "TRC": "Finance",
    "TREX": "Basic Materials",
    "TRGP": "Utilities",
    "TRIN": "Finance",
    "TRLV": "Health Care",
    "TRN": "Industrials",
    "TRNO": "Finance",
    "TROX": "Basic Materials",
    "TRP": "Utilities",
    "TRTX": "Real Estate",
    "TRU": "Finance",
    "TRV": "Finance",
    "TS": "Industrials",
    "TSI": "Finance",
    "TSLX": "Finance",
    "TSM": "Technology",
    "TSN": "Consumer Staples",
    "TSQ": "Consumer Discretionary",
    "TT": "Industrials",
    "TTAM": "Industrials",
    "TTC": "Consumer Discretionary",
    "TTE": "Energy",
    "TTI": "Energy",
    "TU": "Telecommunications",
    "TUYA": "Technology",
    "TV": "Industrials",
    "TVC": "Utilities",
    "TVE": "Utilities",
    "TWI": "Industrials",
    "TWLO": "Technology",
    "TWN": "Finance",
    "TX": "Industrials",
    "TXNM": "Utilities",
    "TXT": "Industrials",
    "TY": "Finance",
    "TYG": "Finance",
    "TYL": "Technology",
    "U": "Technology",
    "UA": "Consumer Discretionary",
    "UAA": "Consumer Discretionary",
    "UAMY": "Industrials",
    "UBER": "Consumer Discretionary",
    "UBS": "Finance",
    "UCB": "Finance",
    "UDR": "Real Estate",
    "UE": "Finance",
    "UFI": "Consumer Discretionary",
    "UGI": "Utilities",
    "UGP": "Utilities",
    "UHAL": "Consumer Discretionary",
    "UHS": "Health Care",
    "UHT": "Real Estate",
    "UI": "Technology",
    "UIS": "Technology",
    "UL": "Consumer Discretionary",
    "ULS": "Health Care",
    "UMC": "Technology",
    "UMH": "Real Estate",
    "UNF": "Consumer Discretionary",
    "UNFI": "Consumer Discretionary",
    "UNH": "Health Care",
    "UNM": "Finance",
    "UNP": "Industrials",
    "UP": "Consumer Discretionary",
    "UPS": "Industrials",
    "URI": "Consumer Discretionary",
    "USA": "Finance",
    "USB": "Finance",
    "USFD": "Consumer Discretionary",
    "USNA": "Health Care",
    "USPH": "Health Care",
    "UTF": "Finance",
    "UTI": "Real Estate",
    "UTL": "Utilities",
    "UTZ": "Consumer Staples",
    "UVE": "Finance",
    "UVV": "Industrials",
    "UWMC": "Finance",
    "V": "Consumer Discretionary",
    "VAC": "Finance",
    "VACI": "Telecommunications",
    "VAL": "Energy",
    "VALE": "Basic Materials",
    "VATE": "Industrials",
    "VBF": "Finance",
    "VCV": "Finance",
    "VCX": "Unknown",
    "VECA": "Finance",
    "VEEV": "Technology",
    "VEL": "Finance",
    "VET": "Energy",
    "VFC": "Industrials",
    "VG": "Utilities",
    "VGI": "Finance",
    "VGM": "Finance",
    "VGNT": "Consumer Discretionary",
    "VHI": "Basic Materials",
    "VIA": "Technology",
    "VICI": "Real Estate",
    "VII": "Unknown",
    "VIK": "Consumer Discretionary",
    "VIPS": "Consumer Discretionary",
    "VIRT": "Finance",
    "VIST": "Energy",
    "VIV": "Telecommunications",
    "VKQ": "Finance",
    "VLN": "Technology",
    "VLO": "Energy",
    "VLRS": "Consumer Discretionary",
    "VLT": "Finance",
    "VLTO": "Industrials",
    "VMC": "Industrials",
    "VMI": "Industrials",
    "VMO": "Finance",
    "VMRK": "Real Estate",
    "VNO": "Real Estate",
    "VNT": "Industrials",
    "VOYA": "Finance",
    "VOYG": "Industrials",
    "VPG": "Technology",
    "VPV": "Finance",
    "VRT": "Technology",
    "VRTS": "Finance",
    "VSH": "Technology",
    "VST": "Utilities",
    "VSTS": "Consumer Discretionary",
    "VSXY": "Consumer Discretionary",
    "VTEX": "Technology",
    "VTMX": "Finance",
    "VTN": "Finance",
    "VTOL": "Consumer Discretionary",
    "VTR": "Real Estate",
    "VTS": "Energy",
    "VVR": "Finance",
    "VVV": "Industrials",
    "VVX": "Consumer Discretionary",
    "VYX": "Miscellaneous",
    "VZ": "Telecommunications",
    "W": "Consumer Discretionary",
    "WAB": "Industrials",
    "WAL": "Finance",
    "WAT": "Industrials",
    "WBI": "Energy",
    "WBX": "Consumer Discretionary",
    "WCC": "Consumer Discretionary",
    "WCN": "Utilities",
    "WD": "Finance",
    "WDI": "Finance",
    "WDS": "Energy",
    "WEA": "Finance",
    "WEAV": "Technology",
    "WEC": "Utilities",
    "WELL": "Real Estate",
    "WENC": "Finance",
    "WEX": "Consumer Discretionary",
    "WF": "Finance",
    "WFC": "Finance",
    "WFG": "Basic Materials",
    "WGO": "Industrials",
    "WH": "Consumer Discretionary",
    "WHD": "Consumer Discretionary",
    "WHG": "Finance",
    "WHK": "Energy",
    "WHR": "Consumer Discretionary",
    "WIA": "Finance",
    "WIT": "Technology",
    "WIW": "Finance",
    "WK": "Technology",
    "WKC": "Energy",
    "WLK": "Industrials",
    "WLY": "Consumer Discretionary",
    "WLYB": "Consumer Discretionary",
    "WM": "Utilities",
    "WMB": "Utilities",
    "WMK": "Consumer Staples",
    "WMS": "Consumer Discretionary",
    "WNC": "Industrials",
    "WOLF": "Technology",
    "WOR": "Industrials",
    "WPAC": "Finance",
    "WPC": "Real Estate",
    "WPM": "Basic Materials",
    "WPP": "Consumer Discretionary",
    "WRB": "Finance",
    "WRBY": "Health Care",
    "WS": "Industrials",
    "WSM": "Consumer Discretionary",
    "WSO": "Consumer Discretionary",
    "WSO-B": "Unknown",
    "WST": "Health Care",
    "WT": "Finance",
    "WTI": "Energy",
    "WTM": "Finance",
    "WTRG": "Utilities",
    "WTS": "Industrials",
    "WTTR": "Energy",
    "WU": "Consumer Discretionary",
    "WWW": "Consumer Discretionary",
    "WY": "Real Estate",
    "XFLH": "Finance",
    "XFLT": "Finance",
    "XHR": "Consumer Discretionary",
    "XOM": "Energy",
    "XPER": "Technology",
    "XPEV": "Industrials",
    "XPO": "Consumer Discretionary",
    "XPOF": "Consumer Discretionary",
    "XPRO": "Energy",
    "XRN": "Real Estate",
    "XTND": "Industrials",
    "XXI": "Finance",
    "XYF": "Finance",
    "XYL": "Industrials",
    "XYZ": "Technology",
    "XZO": "Technology",
    "YALA": "Technology",
    "YCY": "Unknown",
    "YELP": "Consumer Discretionary",
    "YETI": "Consumer Discretionary",
    "YEXT": "Technology",
    "YMM": "Technology",
    "YOU": "Technology",
    "YPF": "Energy",
    "YRD": "Finance",
    "YSG": "Consumer Discretionary",
    "YSS": "Industrials",
    "YUM": "Consumer Discretionary",
    "YUMC": "Consumer Discretionary",
    "ZBH": "Health Care",
    "ZEPP": "Technology",
    "ZETA": "Technology",
    "ZGN": "Consumer Discretionary",
    "ZH": "Consumer Discretionary",
    "ZIM": "Consumer Discretionary",
    "ZIP": "Technology",
    "ZKH": "Consumer Discretionary",
    "ZTO": "Industrials",
    "ZTR": "Finance",
    "ZTS": "Health Care",
    "ZVIA": "Consumer Staples",
    "ZWS": "Industrials",
}

NYSE_SYMBOLS: list[str] = list(NYSE_SECTORS.keys())
